% =========================================================================
% AI ACKNOWLEDGMENT: This code was generated by Claude (Anthropic) with
% inputs and direction from Peter Martin.
%
% Imager_CNN_ValPos.m -- interpolation test on the CENTER (P9) validation
% positions, per Joel Harley's position-disjoint guidance.
%
% TRAIN: every corner-position sample (P1-P4) from all selected sessions.
% TEST : the P9 cell-center samples from those sessions' validation/ folders
%        -- positions the model has NEVER seen as classes or targets.
%
% Two heads, same conv body and pipeline:
%   1. CLASSIFICATION (the settled 49-way CNN): a P9 sample is necessarily
%      "wrong" as a label; we score the DISTANCE from the predicted corner
%      to the true cell center. Ideal snap = a corner of the P9's own cell
%      (0.530 in away). Chance = distance to a random corner.
%   2. REGRESSION: same body, fc(2) linear output trained on corner (x,y);
%      predicts continuous coordinates for P9 samples.
%
% Preprocessing = canonical pipeline, with all per-session statistics
% (mean-sub, z-score) computed from CORNER samples only and applied to the
% P9 samples (no P9 data influences any statistic).
%
% Env: CNN_LOSO_PARENT, CNN_LOSO_SESSIONS, CNN_LOSO_SETLABEL, CNN_LOSO_EPOCHS
% =========================================================================
clear; clc; close all;
fprintf('=== Imager CNN ValPos: train corners, test cell centers ===\n');

cfg.LR = 1e-3; cfg.BatchSize = 16; cfg.Epochs = 100;
cfg.Conv1 = 32; cfg.Conv2 = 32; cfg.FC1 = 64; cfg.Dropout = 0.3;
cfg.LRDropFactor = 0.5; cfg.LRDropPeriod = 30;
if ~isempty(getenv('CNN_LOSO_EPOCHS')), cfg.Epochs = str2double(getenv('CNN_LOSO_EPOCHS')); end
rng(42);
if usejava('desktop'), figVis = 'on'; else, figVis = 'off'; end

LOADER_DIR = 'C:\Users\peter\Desktop\EM Imaging\Imager Program';
addpath(LOADER_DIR);
thisDir = fileparts(mfilename('fullpath'));
if isempty(thisDir), thisDir = pwd; end
resultsDir = fullfile(fileparts(thisDir), 'results');

parentDir = getenv('CNN_LOSO_PARENT');
sessFilt  = strtrim(getenv('CNN_LOSO_SESSIONS'));
setLabel  = strtrim(getenv('CNN_LOSO_SETLABEL'));
if isempty(setLabel), setLabel = 'valpos'; end
[~, setupName] = fileparts(parentDir);

% ---- enumerate + load sessions ----
dd = dir(parentDir); dd = dd([dd.isdir]); dd = dd(~ismember({dd.name}, {'.','..'}));
names = {dd.name};
if ~isempty(sessFilt)
    toks = strsplit(sessFilt);
    keep = false(size(names));
    for i = 1:numel(names)
        for t = 1:numel(toks)
            if contains(names{i}, toks{t}), keep(i) = true; end
        end
    end
    names = names(keep);
end
nSess = numel(names);
fprintf('Sessions (%d): %s\n', nSess, strjoin(names, ', '));

pairs = zeros(16, 2);            % [magRow phaseRow] per S-param (all 16)
for k = 1:16, pairs(k,:) = [2*k-1, 2*k]; end
K = 16;

XtrAll = []; ytrAll = {}; XteAll = []; teMeta = [];   % te: [sess, row, col]
xyLookup = containers.Map('KeyType','char','ValueType','any');

for s = 1:nSess
    fld = fullfile(parentDir, names{s});
    loaded = loadHunterVnaFolder(fld);
    nFreq = loaded.numFreqPoints;
    % complex baseline
    baseC = zeros(K, nFreq);
    for k = 1:K
        baseC(k,:) = loaded.baseline(pairs(k,1),:) .* exp(1j*deg2rad(loaded.baseline(pairs(k,2),:)));
    end
    % ---- corner samples ----
    nPos = size(loaded.data, 1); T = loaded.trialCount;
    Yc = []; lbls = {};
    for p = 1:nPos
        lbl = loaded.data{p,1};
        xyLookup(lbl) = loaded.xyCoords(p,:);
        for t = 1:T
            raw = loaded.data{p, t+1};
            if any(isnan(raw(:))), continue; end
            Sc = zeros(K, nFreq);
            for k = 1:K
                Sc(k,:) = raw(pairs(k,1),:) .* exp(1j*deg2rad(raw(pairs(k,2),:)));
            end
            Yc(:,:,end+1) = Sc - baseC; %#ok<SAGROW>
            lbls{end+1} = lbl;          %#ok<AGROW>
        end
    end
    Yc = Yc(:,:,2:end);   % drop the implicit first empty page
    % ---- P9 validation samples ----
    vf = dir(fullfile(fld, 'validation', 'R*C*P9_T*.csv'));
    Yv = []; vMeta = [];
    for f = 1:numel(vf)
        tok = regexp(vf(f).name, '^R(\d+)C(\d+)P9_T\d+\.csv$', 'tokens');
        if isempty(tok), continue; end
        r9 = str2double(tok{1}{1}); c9 = str2double(tok{1}{2});
        mat = readmatrix(fullfile(fld, 'validation', vf(f).name));
        if size(mat,1) ~= nFreq || size(mat,2) ~= 33, continue; end
        raw = mat(:, 2:end)';
        Sc = zeros(K, nFreq);
        for k = 1:K
            Sc(k,:) = raw(pairs(k,1),:) .* exp(1j*deg2rad(raw(pairs(k,2),:)));
        end
        Yv(:,:,end+1) = Sc - baseC; %#ok<SAGROW>
        vMeta(end+1,:) = [s r9 c9]; %#ok<AGROW>
    end
    Yv = Yv(:,:,2:end);
    fprintf('  %s: %d corner samples, %d P9 samples\n', names{s}, size(Yc,3), size(Yv,3));
    % ---- per-session stats from CORNERS ONLY, applied to both ----
    mYc = mean(Yc, 3);
    Yc = Yc - mYc;  Yv = Yv - mYc;
    Xc = [abs(Yc); angle(Yc)];  Xv = [abs(Yv); angle(Yv)];
    mu = mean(Xc, 3); sd = std(Xc, 0, 3) + 1e-8;
    Xc = (Xc - mu) ./ sd;  Xv = (Xv - mu) ./ sd;
    XtrAll = cat(3, XtrAll, Xc);  ytrAll = [ytrAll, lbls]; %#ok<AGROW>
    XteAll = cat(3, XteAll, Xv);  teMeta = [teMeta; vMeta]; %#ok<AGROW>
end

validPos = sort(unique(ytrAll));
nClasses = numel(validPos);
nRows = size(XtrAll, 1); nFreq = size(XtrAll, 2);
XTrain = reshape(XtrAll, nRows, nFreq, 1, []);
XTest  = reshape(XteAll, nRows, nFreq, 1, []);
YTrain = categorical(ytrAll(:), validPos);
cornerXY = zeros(nClasses, 2);
for p = 1:nClasses, cornerXY(p,:) = xyLookup(validPos{p}); end
teXY = [(teMeta(:,3)-0.5) (teMeta(:,2)-0.5)];   % true P9 centers (x=col, y=row)
fprintf('Train: %d samples, %d classes | Test: %d P9 samples\n', ...
    size(XTrain,4), nClasses, size(XTest,4));

execEnv = 'cpu'; if gpuDeviceCount > 0, execEnv = 'gpu'; end
opts = @(final) trainingOptions('adam', 'InitialLearnRate', cfg.LR, ...
    'MaxEpochs', cfg.Epochs, 'MiniBatchSize', cfg.BatchSize, 'Shuffle', 'every-epoch', ...
    'LearnRateSchedule', 'piecewise', 'LearnRateDropFactor', cfg.LRDropFactor, ...
    'LearnRateDropPeriod', cfg.LRDropPeriod, 'Verbose', false, 'ExecutionEnvironment', execEnv);

body = @() [ ...
    imageInputLayer([nRows nFreq 1], 'Normalization', 'zscore', 'Name', 'input')
    convolution2dLayer([min(4,nRows) min(20,nFreq)], cfg.Conv1, 'Padding', 'same')
    batchNormalizationLayer; reluLayer
    convolution2dLayer([min(2,nRows) min(10,nFreq)], cfg.Conv2, 'Padding', 'same')
    batchNormalizationLayer; reluLayer
    fullyConnectedLayer(cfg.FC1); batchNormalizationLayer; reluLayer
    dropoutLayer(cfg.Dropout)];

% ---------------- 1. CLASSIFICATION head ----------------
fprintf('\n--- training CLASSIFICATION head (49-way corners) ---\n'); t0 = tic;
layersC = [body(); fullyConnectedLayer(nClasses); softmaxLayer; classificationLayer];
netC = trainNetwork(XTrain, YTrain, layersC, opts('c'));
fprintf('  trained in %.1fs\n', toc(t0));
predC = classify(netC, XTest);
predXY = cornerXY(double(predC), :);
errC = hypot(predXY(:,1)-teXY(:,1), predXY(:,2)-teXY(:,2));
% per-(session, P9 cell) majority vote
[grp, ~, gid] = unique(teMeta, 'rows');
errCvote = zeros(size(grp,1),1);
for g = 1:size(grp,1)
    m = mode(double(predC(gid==g)));
    v = cornerXY(m,:); tXY = [(grp(g,3)-0.5) (grp(g,2)-0.5)];
    errCvote(g) = hypot(v(1)-tXY(1), v(2)-tXY(2));
end
snapDist = hypot(0.375, 0.375);   % ideal: own-cell corner = 0.530 in
cellHit = mean(errC <= snapDist + 0.02) * 100;
cellHitVote = mean(errCvote <= snapDist + 0.02) * 100;
fprintf('CLASSIFICATION->corner: trial err mean %.3f / median %.3f in | vote err mean %.3f in\n', ...
    mean(errC), median(errC), mean(errCvote));
fprintf('  own-cell corner hit: %.1f%% trials, %.1f%% votes (ideal err %.3f in)\n', ...
    cellHit, cellHitVote, snapDist);

% ---------------- 2. REGRESSION head ----------------
fprintf('\n--- training REGRESSION head (corner x,y) ---\n'); t0 = tic;
tgt = zeros(numel(ytrAll), 2);
for i = 1:numel(ytrAll), tgt(i,:) = xyLookup(ytrAll{i}); end
layersR = [body(); fullyConnectedLayer(2); regressionLayer];
netR = trainNetwork(XTrain, tgt, layersR, opts('r'));
fprintf('  trained in %.1fs\n', toc(t0));
predR = predict(netR, XTest);
errR = hypot(predR(:,1)-teXY(:,1), predR(:,2)-teXY(:,2));
errRvote = zeros(size(grp,1),1);
for g = 1:size(grp,1)
    v = mean(predR(gid==g,:), 1); tXY = [(grp(g,3)-0.5) (grp(g,2)-0.5)];
    errRvote(g) = hypot(v(1)-tXY(1), v(2)-tXY(2));
end
fprintf('REGRESSION: trial err mean %.3f / median %.3f in | mean-of-16 err mean %.3f in\n', ...
    mean(errR), median(errR), mean(errRvote));

% chance baseline: random corner
rc = cornerXY(randi(nClasses, 5000, 1), :);
rt = teXY(randi(size(teXY,1), 5000, 1), :);
fprintf('Chance (random corner): mean err %.3f in\n', mean(hypot(rc(:,1)-rt(:,1), rc(:,2)-rt(:,2))));

% ---- save ----
result = struct('method', 'CNN-valpos', 'setup', setupName, 'sessionSet', setLabel, ...
    'nTrain', size(XTrain,4), 'nTest', size(XTest,4), 'nClasses', nClasses, ...
    'classTrialErrMean', mean(errC), 'classTrialErrMedian', median(errC), ...
    'classVoteErrMean', mean(errCvote), 'classCellHitPct', cellHit, ...
    'classCellHitVotePct', cellHitVote, 'idealSnapIn', snapDist, ...
    'regTrialErrMean', mean(errR), 'regTrialErrMedian', median(errR), ...
    'regVoteErrMean', mean(errRvote), 'cnnConfig', cfg);
tag = sprintf('%s_%s_valpos', matlab.lang.makeValidName(setupName), setLabel);
fid = fopen(fullfile(resultsDir, sprintf('cnn_%s.json', tag)), 'w');
fprintf(fid, '%s', jsonencode(result, 'PrettyPrint', true)); fclose(fid);
save(fullfile(resultsDir, sprintf('cnn_%s.mat', tag)), 'result', 'predR', 'predXY', 'teXY', 'teMeta', 'errC', 'errR');

% scatter figure: true centers vs predictions
figSp = figure('Position', [100 100 720 640], 'Visible', figVis); hold on;
scatter(cornerXY(:,1), cornerXY(:,2), 22, [0.75 0.75 0.75], 'filled');
scatter(teXY(:,1), teXY(:,2), 90, [0.13 0.45 0.13], 'filled');
scatter(predR(:,1), predR(:,2), 14, [0.75 0 0], 'filled', 'MarkerFaceAlpha', 0.35);
for g = 1:size(grp,1)
    v = mean(predR(gid==g,:), 1); tXY = [(grp(g,3)-0.5) (grp(g,2)-0.5)];
    plot([v(1) tXY(1)], [v(2) tXY(2)], '-', 'Color', [0.75 0 0 0.6], 'LineWidth', 1.2);
end
set(gca, 'YDir', 'reverse'); axis equal; grid on;
legend({'trained corners', 'true P9 centers', 'regression predictions'}, 'Location', 'southoutside', 'Orientation', 'horizontal');
xlabel('X (inches)'); ylabel('Y (inches)');
title(sprintf('Unseen cell centers: regression err %.3f in (mean-of-16), classification snap %.3f in', ...
    mean(errRvote), mean(errCvote)));
saveas(figSp, fullfile(resultsDir, sprintf('cnn_%s_scatter.png', tag)));
fprintf('\nSaved results + scatter to %s\n', resultsDir);
