% =========================================================================
% AI ACKNOWLEDGMENT: This code was generated by Claude (Anthropic) with
% inputs and direction from Peter Martin.
%
% Imager_CNN_LOPO.m -- Leave-One-Position-Out REGRESSION (Joel Harley
% protocol: training and testing data completely unique in location).
%
% For each of the 49 corner positions: hold out ALL sessions' samples of
% that position, train the regression CNN (corner (x,y) targets) on the
% other 48 positions, predict the held-out samples. 49 trainings, one
% MATLAB process (data loaded once).
%
% Leakage hygiene: per-session mean-sub + z-score statistics are computed
% EXCLUDING the held-out position, then applied to both train and test.
%
% Env: CNN_LOSO_PARENT, CNN_LOSO_SESSIONS, CNN_LOSO_SETLABEL,
%      CNN_LOSO_EPOCHS (default 20 - fast regime)
% =========================================================================
clear; clc; close all;
fprintf('=== Imager CNN LOPO: leave-one-POSITION-out regression ===\n');

cfg.LR = 1e-3; cfg.BatchSize = 16; cfg.Epochs = 20;
cfg.Conv1 = 32; cfg.Conv2 = 32; cfg.FC1 = 64; cfg.Dropout = 0.3;
cfg.LRDropFactor = 0.5; cfg.LRDropPeriod = 30;
if ~isempty(getenv('CNN_LOSO_EPOCHS')), cfg.Epochs = str2double(getenv('CNN_LOSO_EPOCHS')); end
rng(42);
if usejava('desktop'), figVis = 'on'; else, figVis = 'off'; end
addpath('C:\Users\peter\Desktop\EM Imaging\Imager Program');
thisDir = fileparts(mfilename('fullpath'));
if isempty(thisDir), thisDir = pwd; end
resultsDir = fullfile(fileparts(thisDir), 'results');

parentDir = getenv('CNN_LOSO_PARENT');
sessFilt  = strtrim(getenv('CNN_LOSO_SESSIONS'));
setLabel  = strtrim(getenv('CNN_LOSO_SETLABEL'));
if isempty(setLabel), setLabel = 'lopo'; end
[~, setupName] = fileparts(parentDir);

dd = dir(parentDir); dd = dd([dd.isdir]); dd = dd(~ismember({dd.name}, {'.','..'}));
names = {dd.name};
if ~isempty(sessFilt)
    toks = strsplit(sessFilt); keep = false(size(names));
    for i = 1:numel(names)
        for t = 1:numel(toks), if contains(names{i}, toks{t}), keep(i) = true; end, end
    end
    names = names(keep);
end
nSess = numel(names);
fprintf('Sessions (%d): %s\n', nSess, strjoin(names, ', '));

pairs = zeros(16, 2); for k = 1:16, pairs(k,:) = [2*k-1, 2*k]; end
K = 16;

% ---- load all sessions: keep complex Y (baseline-subtracted), labels ----
Yall = {}; lblAll = {}; sessIdx = [];
xyLookup = containers.Map('KeyType','char','ValueType','any');
for s = 1:nSess
    loaded = loadHunterVnaFolder(fullfile(parentDir, names{s}));
    nFreq = loaded.numFreqPoints;
    baseC = zeros(K, nFreq);
    for k = 1:K
        baseC(k,:) = loaded.baseline(pairs(k,1),:) .* exp(1j*deg2rad(loaded.baseline(pairs(k,2),:)));
    end
    for p = 1:size(loaded.data, 1)
        lbl = loaded.data{p,1};
        xyLookup(lbl) = loaded.xyCoords(p,:);
        for t = 1:loaded.trialCount
            raw = loaded.data{p, t+1};
            if any(isnan(raw(:))), continue; end
            Sc = zeros(K, nFreq);
            for k = 1:K
                Sc(k,:) = raw(pairs(k,1),:) .* exp(1j*deg2rad(raw(pairs(k,2),:)));
            end
            Yall{end+1} = Sc - baseC;  %#ok<AGROW>
            lblAll{end+1} = lbl;       %#ok<AGROW>
            sessIdx(end+1) = s;        %#ok<AGROW>
        end
    end
    fprintf('  %s loaded\n', names{s});
end
N = numel(Yall);
validPos = sort(unique(lblAll));
nPos = numel(validPos);
tgtAll = zeros(N, 2);
for i = 1:N, tgtAll(i,:) = xyLookup(lblAll{i}); end
nFreq = size(Yall{1}, 2); nRows = 2*K;
fprintf('%d samples, %d positions, %d sessions\n', N, nPos, nSess);

execEnv = 'cpu'; if gpuDeviceCount > 0, execEnv = 'gpu'; end
opts = trainingOptions('adam', 'InitialLearnRate', cfg.LR, 'MaxEpochs', cfg.Epochs, ...
    'MiniBatchSize', cfg.BatchSize, 'Shuffle', 'every-epoch', ...
    'LearnRateSchedule', 'piecewise', 'LearnRateDropFactor', cfg.LRDropFactor, ...
    'LearnRateDropPeriod', cfg.LRDropPeriod, 'Verbose', false, 'ExecutionEnvironment', execEnv);
layersFor = @() [ ...
    imageInputLayer([nRows nFreq 1], 'Normalization', 'zscore')
    convolution2dLayer([min(4,nRows) min(20,nFreq)], cfg.Conv1, 'Padding', 'same')
    batchNormalizationLayer; reluLayer
    convolution2dLayer([min(2,nRows) min(10,nFreq)], cfg.Conv2, 'Padding', 'same')
    batchNormalizationLayer; reluLayer
    fullyConnectedLayer(cfg.FC1); batchNormalizationLayer; reluLayer
    dropoutLayer(cfg.Dropout)
    fullyConnectedLayer(2); regressionLayer];

perHold = struct('label', {}, 'x', {}, 'y', {}, 'trialErrMean', {}, 'voteErr', {});
allTrialErr = [];
tAll = tic;
for h = 1:nPos
    hp = validPos{h};
    isTe = strcmp(lblAll, hp);
    t0 = tic;
    % per-session stats EXCLUDING the held-out position
    Xtr = []; Xte = []; ytr = []; teSess = [];
    for s = 1:nSess
        selTr = (sessIdx == s) & ~isTe;
        selTe = (sessIdx == s) & isTe;
        Ytr = cat(3, Yall{selTr});  Yte = cat(3, Yall{selTe});
        mY = mean(Ytr, 3);
        Ytr = Ytr - mY;  Yte = Yte - mY;
        Xa = [abs(Ytr); angle(Ytr)];  Xb = [abs(Yte); angle(Yte)];
        mu = mean(Xa, 3); sd = std(Xa, 0, 3) + 1e-8;
        Xa = (Xa - mu) ./ sd;  Xb = (Xb - mu) ./ sd;
        Xtr = cat(3, Xtr, Xa);  Xte = cat(3, Xte, Xb);
        ytr = [ytr; tgtAll(selTr, :)]; %#ok<AGROW>
        teSess = [teSess; repmat(s, sum(selTe), 1)]; %#ok<AGROW>
    end
    XTrain = reshape(Xtr, nRows, nFreq, 1, []);
    XTest  = reshape(Xte, nRows, nFreq, 1, []);
    net = trainNetwork(XTrain, ytr, layersFor(), opts);
    pred = predict(net, XTest);
    tXY = xyLookup(hp);
    errs = hypot(pred(:,1) - tXY(1), pred(:,2) - tXY(2));
    vote = mean(pred, 1);
    vErr = hypot(vote(1) - tXY(1), vote(2) - tXY(2));
    allTrialErr = [allTrialErr; errs]; %#ok<AGROW>
    perHold(end+1) = struct('label', hp, 'x', tXY(1), 'y', tXY(2), ...
        'trialErrMean', mean(errs), 'voteErr', vErr); %#ok<AGROW>
    fprintf('  hold %2d/%d %s: trial err %.3f in, vote err %.3f in  (%.0fs)\n', ...
        h, nPos, hp, mean(errs), vErr, toc(t0));
end
fprintf('\nLOPO REGRESSION (%d holds, %.1f min total)\n', nPos, toc(tAll)/60);
fprintf('  per-trial error : mean %.3f  median %.3f in\n', mean(allTrialErr), median(allTrialErr));
fprintf('  per-hold vote   : mean %.3f  median %.3f in\n', ...
    mean([perHold.voteErr]), median([perHold.voteErr]));

result = struct('method', 'CNN-LOPO-regression', 'setup', setupName, ...
    'sessionSet', setLabel, 'epochs', cfg.Epochs, 'nHolds', nPos, ...
    'trialErrMean', mean(allTrialErr), 'trialErrMedian', median(allTrialErr), ...
    'voteErrMean', mean([perHold.voteErr]), 'voteErrMedian', median([perHold.voteErr]), ...
    'perHold', perHold, 'cnnConfig', cfg);
tag = sprintf('%s_%s_lopo', matlab.lang.makeValidName(setupName), setLabel);
fid = fopen(fullfile(resultsDir, sprintf('cnn_%s.json', tag)), 'w');
fprintf(fid, '%s', jsonencode(result, 'PrettyPrint', true)); fclose(fid);
save(fullfile(resultsDir, sprintf('cnn_%s.mat', tag)), 'result');

% error map
figE = figure('Position', [100 100 680 620], 'Visible', figVis);
scatter([perHold.x], [perHold.y], 260, [perHold.voteErr], 'filled', 'MarkerEdgeColor', 'w');
colormap(flipud(parula)); cb = colorbar; cb.Label.String = 'LOPO vote error (inches)';
set(gca, 'YDir', 'reverse'); axis equal; grid on;
xlabel('X (inches)'); ylabel('Y (inches)');
title(sprintf('LOPO regression error by held-out position - mean %.3f in', mean([perHold.voteErr])));
saveas(figE, fullfile(resultsDir, sprintf('cnn_%s_map.png', tag)));
fprintf('Saved %s results + map\n', tag);
