% =========================================================================
% AI ACKNOWLEDGMENT: This code was generated by Claude (Anthropic) with
% inputs and direction from Peter Martin.
%
% Imager_CNN_LOSO.m  --  Leave-One-Session-Out CNN for Hunter 4-port data
%
% This is the LOSO counterpart to Imager_ML_MultiSession.m.  It keeps the
% SAME CNN METHOD as the original single-stage classifier:
%
%     imageInputLayer([rows freq 1], 'zscore')
%     conv2d([min(4,rows) 20], 32) -> BN -> ReLU
%     conv2d([min(2,rows) 10], 32) -> BN -> ReLU
%     fc(64) -> BN -> ReLU -> dropout(0.3)
%     fc(nClasses) -> softmax -> classification
%     adam, 100 epochs, batch 16, LR 1e-3 piecewise
%
% The ONLY change to the training/evaluation protocol is:
%   ORIGINAL:  one combined dataset, 75/25 stratified split
%   THIS FILE: N sessions, N-fold LEAVE-ONE-SESSION-OUT
%              (train on N-1 sessions, test on the held-out session)
%
% LOSO removes the session-drift confound that inflates a 75/25 split, so
% the number it reports is an honest cross-session generalization accuracy
% -- directly comparable to the Python MLP LOSO in ../mlp_python.
%
% It also lets you restrict the antennas used, from the SAME 4-port data:
%   - ALL     : all 16 S-parameters (4 antennas)          -> 32 rows
%   - PAIR    : 2 antennas, e.g. [1 3] or [2 4]           ->  8 rows
%               (uses S11,S13,S31,S33 for the [1 3] pair)
%   - SINGLE  : 1 antenna, e.g. antenna 1                 ->  2 rows
%               (uses only S11 -- one reflection coefficient)
%
% DATA: point it at a PARENT folder that holds the per-session subfolders
% for ONE phantom setup (empty / F4 / F5).  Each subfolder must be a Hunter
% VNA session (baseline_T*.csv + RnCmPp_T*.csv), e.g.:
%
%   ...\Sam Antennas\MediumAntenna\Separated\June18\
%       BreastPhantom_A3_FishingWeight_20260618_1530\
%       BreastPhantom_A3_FishingWeight_20260618_1547\
%       BreastPhantom_A3_FishingWeight_20260618_1611\
%
% Reuses loadHunterVnaFolder.m from the Imager Program folder.
% =========================================================================

clear; clc; close all;

fprintf('=========================================================\n');
fprintf('  Imager CNN  --  Leave-One-Session-Out (Hunter 4-port)\n');
fprintf('=========================================================\n\n');

%% -----------------------------------------------------------------------
%  CONFIG  (same tunable CNN hyper-parameters as the original single-stage)
%  ----------------------------------------------------------------------
cfg.LR           = 1e-3;
cfg.BatchSize    = 16;
cfg.Epochs       = 100;
cfg.Conv1        = 32;
cfg.Conv2        = 32;
cfg.FC1          = 64;
cfg.Dropout      = 0.3;
cfg.LRDropFactor = 0.5;
cfg.LRDropPeriod = 30;
cfg.showPlots    = false;   % set true to watch each fold's training-progress

% Optional headless override: set CNN_LOSO_EPOCHS to run fewer epochs (smoke test)
if ~isempty(getenv('CNN_LOSO_EPOCHS'))
    cfg.Epochs = str2double(getenv('CNN_LOSO_EPOCHS'));
    fprintf('[override] Epochs = %d\n', cfg.Epochs);
end

rng(42);

% Figures are always saved to results/; only make them visible with a desktop.
if usejava('desktop'), figVis = 'on'; else, figVis = 'off'; end

% Make loadHunterVnaFolder.m available (it lives in the Imager Program folder)
LOADER_DIR = 'C:\Users\peter\Desktop\EM Imaging\Imager Program';
if exist(fullfile(LOADER_DIR, 'loadHunterVnaFolder.m'), 'file')
    addpath(LOADER_DIR);
else
    warning('loadHunterVnaFolder.m not found in %s -- select it if prompted.', LOADER_DIR);
end

thisDir = fileparts(mfilename('fullpath'));
if isempty(thisDir), thisDir = pwd; end
resultsDir = fullfile(fileparts(thisDir), 'results');
if ~isfolder(resultsDir), mkdir(resultsDir); end

%% -----------------------------------------------------------------------
%  1. SELECT DATA  (parent folder holding the per-session subfolders)
%  ----------------------------------------------------------------------
defaultParent = ['C:\Users\peter\Desktop\EM Imaging\BreastPhantom\HunterVNA\' ...
                 'DataMeasurements\Sam Antennas\MediumAntenna\Separated\June18'];
if ~isfolder(defaultParent), defaultParent = pwd; end

if ~isempty(getenv('CNN_LOSO_PARENT'))
    parentDir = getenv('CNN_LOSO_PARENT');       % headless override
    fprintf('[override] parent folder = %s\n', parentDir);
else
    fprintf('Select the PARENT folder that contains this setup''s session subfolders.\n');
    fprintf('(Each subfolder = one recording session for the same phantom setup.)\n');
    parentDir = uigetdir(defaultParent, 'Select parent folder (holds session subfolders)');
    if isequal(parentDir, 0)
        fprintf('Cancelled.\n'); return;
    end
end

[sessions, sessNames] = loadAllSessions(parentDir);
nSess = numel(sessions);
if nSess < 2
    error('LOSO needs at least 2 sessions; found %d in %s', nSess, parentDir);
end
fprintf('\nLoaded %d sessions:\n', nSess);
for s = 1:nSess
    fprintf('   [%d] %-45s  %d positions, %d trials\n', s, sessNames{s}, ...
        numel(sessions{s}.posLabels), sessions{s}.trialCount);
end

% Setup label (folder name) for output naming
[~, setupName] = fileparts(parentDir);
if isempty(setupName), setupName = 'setup'; end

% Session-set label: distinguishes e.g. all-5 vs latter-3 runs in filenames
% and in the comparison table.  Defaults to "<N>sess"; override with
% CNN_LOSO_SETLABEL (e.g. "last3").
setLabel = strtrim(getenv('CNN_LOSO_SETLABEL'));
if isempty(setLabel), setLabel = sprintf('%dsess', nSess); end
if strcmp(strtrim(getenv('CNN_LOSO_NO_MEANSUB')), '1')
    setLabel = [setLabel '-nomean'];    % keep ablation outputs separate
end
fprintf('Session set: %s\n', setLabel);

%% -----------------------------------------------------------------------
%  2. CHOOSE ANTENNA SUBSET  (interactive)
%  ----------------------------------------------------------------------
reflOnly = strcmp(strtrim(getenv('CNN_LOSO_REFL_ONLY')), '1');  % Sii only, no transmission
if ~isempty(getenv('CNN_LOSO_ANT_MODE'))
    % headless override: CNN_LOSO_ANT_MODE = all|pair|single, CNN_LOSO_PORTS = "1 3"
    % CNN_LOSO_REFL_ONLY = 1  -> use only reflection S-parameters (diagonal).
    antennaMode = lower(strtrim(getenv('CNN_LOSO_ANT_MODE')));
    ports = sort(unique(str2num(getenv('CNN_LOSO_PORTS')))); %#ok<ST2NM>
    if strcmp(antennaMode, 'all') || isempty(ports), ports = 1:4; antennaMode = 'all'; end
    if reflOnly, antennaMode = 'refl'; end   % tag/label as reflection-only
    fprintf('[override] antenna = %s  ports [%s]  reflOnly=%d\n', antennaMode, num2str(ports), reflOnly);
else
    fprintf('\n--- Antenna subset ---\n');
    fprintf('  1. ALL      -- all 4 antennas (16 S-parameters, 32 rows)\n');
    fprintf('  2. PAIR     -- 2 antennas (e.g. 1 & 3, or 2 & 4)\n');
    fprintf('  3. SINGLE   -- 1 antenna (reflection only, e.g. antenna 1 -> S11)\n');
    modeResp = input('Choice [1]: ', 's');
    if isempty(modeResp), modeResp = '1'; end

    switch strtrim(modeResp)
        case '2'
            antennaMode = 'pair';
            pr = input('Which two antennas? enter as e.g. "1 3" or "2 4" [1 3]: ', 's');
            if isempty(pr), pr = '1 3'; end
            ports = sort(unique(str2num(pr))); %#ok<ST2NM>
            if numel(ports) ~= 2 || any(ports < 1) || any(ports > 4)
                error('PAIR needs exactly two antenna numbers in 1..4 (got "%s")', pr);
            end
        case '3'
            antennaMode = 'single';
            pr = input('Which antenna? 1..4 [1]: ', 's');
            if isempty(pr), pr = '1'; end
            ports = str2double(pr);
            if ~ismember(ports, 1:4)
                error('SINGLE needs one antenna number in 1..4 (got "%s")', pr);
            end
        otherwise
            antennaMode = 'all';
            ports = 1:4;
    end
end

[selRows, sparamNames, sparamPairs] = antennaRows(ports, reflOnly);

% Input representation: raw (mag+phase image, original CNN) | physics (mag/
% phase/real/imag + IFFT/TDR rows per S-param) | tdr (IFFT/TDR envelope only).
inputMode = lower(strtrim(getenv('CNN_LOSO_INPUT')));
if isempty(inputMode), inputMode = 'raw'; end
N_TDR_BINS = 64;

% Classifier structure: single-stage (default) or hierarchical quadrant->position.
hierMode = strcmp(strtrim(getenv('CNN_LOSO_HIER')), '1');
if hierMode, clfTag = 'hier_'; else, clfTag = ''; end

tag = sprintf('%s_%s_%s%s_%s_ant%s', matlab.lang.makeValidName(setupName), setLabel, ...
              clfTag, inputMode, antennaMode, strrep(num2str(ports), '  ', '-'));
fprintf('Antenna mode: %s   ports [%s]   input=%s\n', upper(antennaMode), num2str(ports), inputMode);
fprintf('S-parameters used (%d): %s\n', numel(sparamNames), strjoin(sparamNames, ', '));

%% -----------------------------------------------------------------------
%  3. BUILD PER-SESSION SAMPLE TENSORS
%     (per-session baseline subtraction + antenna row-subset)
%     -- this is the same feature construction as the original single-stage
%        program with per-session subtraction.
%  ----------------------------------------------------------------------
fprintf('\n--- Building per-session samples ---\n');
built = cell(nSess, 1);
posSetPerSess = cell(nSess, 1);
for s = 1:nSess
    built{s} = buildSession(sessions{s}, selRows, sparamPairs, inputMode, N_TDR_BINS);
    posSetPerSess{s} = unique(built{s}.posLabel);
    fprintf('   session %d: %d samples across %d positions\n', ...
        s, numel(built{s}.posLabel), numel(posSetPerSess{s}));
end

% Valid positions = those present in EVERY session (so labels line up across folds)
validPos = posSetPerSess{1};
for s = 2:nSess
    validPos = intersect(validPos, posSetPerSess{s});
end
validPos = sort(validPos);
nClasses = numel(validPos);
if nClasses < 2
    error('Fewer than 2 positions common to all sessions -- cannot classify.');
end
fprintf('Common positions across all sessions: %d  (chance = %.2f%%)\n', ...
    nClasses, 100/nClasses);

% Image dimensions depend on the input representation (set from built tensor).
numSParamRows = size(built{1}.X, 1);
numFreqPoints = size(built{1}.X, 2);
fprintf('CNN input image: %d rows x %d cols  (input=%s)\n', numSParamRows, numFreqPoints, inputMode);

% Quadrant split (for hierarchical mode): midpoint of the measured rows/cols.
vr = zeros(nClasses, 1); vc = zeros(nClasses, 1);
for pp = 1:nClasses
    tok = regexp(validPos{pp}, 'R(\d+)C(\d+)', 'tokens');
    vr(pp) = str2double(tok{1}{1}); vc(pp) = str2double(tok{1}{2});
end
ur = sort(unique(vr)); uc = sort(unique(vc));
rowMid = ur(floor(numel(ur)/2)); colMid = uc(floor(numel(uc)/2));
if hierMode
    quadCount = zeros(1,4);
    for pp = 1:nClasses, quadCount(quadOf(validPos{pp}, rowMid, colMid)) = quadCount(quadOf(validPos{pp}, rowMid, colMid)) + 1; end
    fprintf('HIERARCHICAL: rowMid=%d colMid=%d  positions/quadrant = [%s]\n', ...
        rowMid, colMid, num2str(quadCount));
end

%% -----------------------------------------------------------------------
%  4. EXECUTION ENVIRONMENT
%  ----------------------------------------------------------------------
if gpuDeviceCount > 0
    execEnv = 'gpu';
    fprintf('\nGPU detected (%s) -- training on GPU.\n', gpuDevice().Name);
else
    execEnv = 'cpu';
    fprintf('\nNo GPU -- training on CPU.\n');
end

%% -----------------------------------------------------------------------
%  5. LEAVE-ONE-SESSION-OUT LOOP
%  ----------------------------------------------------------------------
fprintf('\n=== %d-fold LEAVE-ONE-SESSION-OUT ===\n', nSess);
foldTrialAcc = zeros(nSess, 1);
foldPosAcc   = zeros(nSess, 1);
posCorrectCount = containers.Map('KeyType', 'char', 'ValueType', 'double');
posTotalCount   = containers.Map('KeyType', 'char', 'ValueType', 'double');
for p = 1:nClasses
    posCorrectCount(validPos{p}) = 0;
    posTotalCount(validPos{p})   = 0;
end

allTrueTest = {};   % accumulated over folds (for a global confusion matrix)
allPredTest = {};

for testS = 1:nSess
    trainS = setdiff(1:nSess, testS);
    t0 = tic;

    % ----- assemble train tensor (valid positions only) -----
    [XTrain, yTrain] = gatherSamples(built(trainS), validPos);
    [XTest,  yTest]  = gatherSamples(built(testS),  validPos);

    YTrain = categorical(yTrain, validPos);
    YTest  = categorical(yTest,  validPos);

    % ----- train + predict: single-stage or hierarchical quadrant->position -----
    if hierMode
        quadTrain = zeros(numel(yTrain), 1);
        for ii = 1:numel(yTrain), quadTrain(ii) = quadOf(yTrain{ii}, rowMid, colMid); end
        predCell = predictHierCNN(XTrain, yTrain, XTest, quadTrain, ...
                                  numSParamRows, numFreqPoints, cfg, execEnv);
        predTest = categorical(predCell, validPos);
    else
        net = trainCNN(XTrain, YTrain, numSParamRows, numFreqPoints, nClasses, cfg, execEnv);
        predTest = classify(net, XTest);
    end

    % ----- evaluate: per-trial + per-position majority vote -----
    trialAcc = mean(predTest == YTest) * 100;

    [posAcc, perPos] = perPositionVote(cellstr(YTest), cellstr(predTest), validPos);
    foldTrialAcc(testS) = trialAcc;
    foldPosAcc(testS)   = posAcc;

    % accumulate per-position hit/total across folds
    fnames = fieldnames(perPos);
    for k = 1:numel(fnames)
        keyPos = perPos.(fnames{k}).label;
        posTotalCount(keyPos)   = posTotalCount(keyPos) + 1;
        posCorrectCount(keyPos) = posCorrectCount(keyPos) + perPos.(fnames{k}).correct;
    end

    allTrueTest = [allTrueTest; cellstr(YTest)];   %#ok<AGROW>
    allPredTest = [allPredTest; cellstr(predTest)];%#ok<AGROW>

    fprintf('  fold test=%d (%s):  trial=%5.2f%%   position-vote=%5.2f%%   (%.1fs)\n', ...
        testS, sessNames{testS}, trialAcc, posAcc, toc(t0));
end

losoTrialMean = mean(foldTrialAcc);
losoTrialStd  = std(foldTrialAcc);
losoPosMean   = mean(foldPosAcc);
losoPosStd    = std(foldPosAcc);

fprintf('\n---------------------------------------------------------\n');
fprintf('  LOSO trial-level    : %.2f +/- %.2f %%\n', losoTrialMean, losoTrialStd);
fprintf('  LOSO position-vote  : %.2f +/- %.2f %%\n', losoPosMean, losoPosStd);
fprintf('  Chance              : %.2f %%  (%d-way)\n', 100/nClasses, nClasses);
fprintf('---------------------------------------------------------\n');

%% -----------------------------------------------------------------------
%  6. SAVE RESULTS  (json + mat) and FIGURES
%  ----------------------------------------------------------------------
% per-position accuracy averaged across folds
posAccMap = struct('label', {}, 'x', {}, 'y', {}, 'acc', {});
xyLookup = buildXYLookup(sessions);
for p = 1:nClasses
    lbl = validPos{p};
    tot = posTotalCount(lbl);
    acc = 0; if tot > 0, acc = 100 * posCorrectCount(lbl) / tot; end
    xy = [NaN NaN]; if isKey(xyLookup, lbl), xy = xyLookup(lbl); end
    posAccMap(end+1) = struct('label', lbl, 'x', xy(1), 'y', xy(2), 'acc', acc); %#ok<AGROW>
end

result = struct();
result.method        = 'CNN';
result.setup         = setupName;
result.sessionSet    = setLabel;
result.inputKind     = inputMode;
result.classifier    = 'single';
if hierMode, result.classifier = 'hierarchical'; end
result.antennaMode   = antennaMode;
result.ports         = ports;
result.sparams       = {sparamNames{:}};
result.numRows       = numSParamRows;
result.numSessions   = nSess;
result.sessionNames  = {sessNames{:}};
result.numClasses    = nClasses;
result.chancePct     = 100/nClasses;
result.foldTrialAcc  = foldTrialAcc(:)';
result.foldPosAcc    = foldPosAcc(:)';
result.losoTrialMean = losoTrialMean;
result.losoTrialStd  = losoTrialStd;
result.losoPosMean   = losoPosMean;
result.losoPosStd    = losoPosStd;
result.perPosition   = posAccMap;
result.cnnConfig     = cfg;

jsonPath = fullfile(resultsDir, sprintf('cnn_loso_%s.json', tag));
fid = fopen(jsonPath, 'w'); fprintf(fid, '%s', jsonencode(result, 'PrettyPrint', true)); fclose(fid);
fprintf('\nSaved %s\n', jsonPath);
save(fullfile(resultsDir, sprintf('cnn_loso_%s.mat', tag)), 'result');

% ----- bar chart of per-fold + mean -----
figBar = figure('Name', 'CNN LOSO', 'Position', [100 100 900 480], 'Visible', figVis);
barVals = [foldPosAcc; losoPosMean];
barLbls = [arrayfun(@(k) sprintf('test=%d', k), 1:nSess, 'uni', 0), {'LOSO mean'}];
b = bar(barVals, 0.7); b.FaceColor = 'flat';
b.CData(1:nSess, :) = repmat([0.23 0.36 0.49], nSess, 1);
b.CData(end, :)     = [0.12 0.33 0.51];
hold on; yline(100/nClasses, '--k', sprintf('chance %.1f%%', 100/nClasses));
for i = 1:numel(barVals)
    text(i, barVals(i)+1.5, sprintf('%.0f', barVals(i)), 'HorizontalAlignment', 'center');
end
set(gca, 'XTick', 1:numel(barLbls), 'XTickLabel', barLbls);
ylabel('Per-position vote accuracy (%)'); ylim([0 108]);
title(sprintf('CNN LOSO  --  %s  --  %s (ports %s)  --  %d-way', ...
    setupName, upper(antennaMode), num2str(ports), nClasses), 'Interpreter', 'none');
grid on;
saveas(figBar, fullfile(resultsDir, sprintf('cnn_loso_%s_bars.png', tag)));

% ----- spatial overlay of per-position accuracy -----
figSp = figure('Name', 'CNN LOSO spatial', 'Position', [150 120 640 620], 'Visible', figVis);
xs = [posAccMap.x]; ys = [posAccMap.y]; accs = [posAccMap.acc];
scatter(xs, ys, 260, accs, 'filled', 'MarkerEdgeColor', 'k'); hold on;
for i = 1:numel(accs)
    text(xs(i), ys(i), sprintf('%.0f', accs(i)), 'HorizontalAlignment', 'center', 'FontSize', 7);
end
colormap(gca, jet); caxis([0 100]); cb = colorbar; cb.Label.String = 'LOSO accuracy (%)';
set(gca, 'YDir', 'reverse'); axis equal; grid on;
xlabel('X (inches)'); ylabel('Y (inches)');
title(sprintf('Per-position LOSO accuracy  --  mean %.1f%%', mean(accs)), 'Interpreter', 'none');
saveas(figSp, fullfile(resultsDir, sprintf('cnn_loso_%s_spatial.png', tag)));

fprintf('Saved figures to %s\n', resultsDir);
fprintf('\nDone.  Compare against the MLP by running ../mlp_python/run_mlp_loso.py\n');
fprintf('with the same setup folder and antenna choice.\n');


% =========================================================================
%  LOCAL FUNCTIONS
% =========================================================================
function [sessions, names] = loadAllSessions(parentDir)
% Enumerate Hunter session subfolders under parentDir and load each.
    d = dir(parentDir);
    subs = d([d.isdir] & ~ismember({d.name}, {'.', '..'}));
    % Optional session subset: CNN_LOSO_SESSIONS = space/comma list of name
    % substrings (e.g. "1432 1454 1516" to keep only those sessions).
    filt = strtrim(getenv('CNN_LOSO_SESSIONS'));
    if ~isempty(filt)
        toks = strsplit(filt, {' ', ','});
        toks = toks(~cellfun(@isempty, toks));
        keep = false(1, numel(subs));
        for ii = 1:numel(subs)
            for tt = 1:numel(toks)
                if contains(subs(ii).name, toks{tt}), keep(ii) = true; break; end
            end
        end
        subs = subs(keep);
        fprintf('[filter] CNN_LOSO_SESSIONS=%s -> %d matching session folders\n', filt, numel(subs));
    end
    % Optional antenna port remap: CNN_LOSO_PORT_REMAP = "2 1 4 3" relabels
    % ports (new port a <- old port list(a)) BEFORE any subsetting, e.g. to
    % bring June18's antenna naming into today's convention.
    remapStr = strtrim(getenv('CNN_LOSO_PORT_REMAP'));
    rowperm = [];
    if ~isempty(remapStr)
        R = str2num(remapStr); %#ok<ST2NM>
        rowperm = zeros(1, 32);
        for a = 1:4
            for b = 1:4
                nidx = (b-1)*4 + a;  oidx = (R(b)-1)*4 + R(a);
                rowperm(2*nidx-1) = 2*oidx-1;  rowperm(2*nidx) = 2*oidx;
            end
        end
        fprintf('[remap] CNN_LOSO_PORT_REMAP=%s (new<-old ports)\n', remapStr);
    end

    sessions = {}; names = {};
    for i = 1:numel(subs)
        p = fullfile(parentDir, subs(i).name);
        if isHunterSession(p)
            fprintf('Loading session: %s\n', subs(i).name);
            try
                L = loadHunterVnaFolder(p);
                if ~isempty(rowperm)
                    L = permuteSessionRows(L, rowperm);
                end
                sessions{end+1} = L;             %#ok<AGROW>
                names{end+1}    = subs(i).name;  %#ok<AGROW>
            catch ME
                fprintf('  SKIP (%s)\n', ME.message);
            end
        end
    end
    % Fallback: maybe parentDir IS a single session -- not enough for LOSO
    if isempty(sessions) && isHunterSession(parentDir)
        error(['Selected folder is a single session. Select the PARENT ' ...
               'folder that contains multiple session subfolders.']);
    end
end

function tf = isHunterSession(p)
% A Hunter session folder has RnCmPp_T*.csv files (and usually a metadata file).
    tf = ~isempty(dir(fullfile(p, 'R*C*P*_T*.csv')));
end

function L = permuteSessionRows(L, rowperm)
% Reorder the 32 S-parameter rows of a loaded session (data cells, baseline,
% baselineAll) by rowperm, so M_new = M_old(rowperm, :). Used to relabel
% antenna ports into a consistent convention.
    for p = 1:size(L.data, 1)
        for t = 2:size(L.data, 2)
            M = L.data{p, t};
            if ~isempty(M) && size(M, 1) == numel(rowperm)
                L.data{p, t} = M(rowperm, :);
            end
        end
    end
    if isfield(L, 'baseline') && size(L.baseline, 1) == numel(rowperm)
        L.baseline = L.baseline(rowperm, :);
    end
    if isfield(L, 'baselineAll') && ~isempty(L.baselineAll) ...
            && size(L.baselineAll, 1) == numel(rowperm)
        L.baselineAll = L.baselineAll(rowperm, :, :);
    end
end

function [rows, names, pairs] = antennaRows(ports, reflOnly)
% Map an antenna (port) list to row indices in the 32-row Hunter matrix.
% Row layout (loadHunterVnaFolder): trace idx = (j-1)*4 + i for S_{ij},
% mag row = 2*idx-1, phase row = 2*idx.  We keep S_{ij} where BOTH i and j
% are in the selected port set (reflections + mutual couplings within the set).
% reflOnly = true keeps ONLY the reflections S_ii (no transmission).
% pairs: K x 2 = [magRow phaseRow] per selected S-param (for physics/tdr modes).
    if nargin < 2, reflOnly = false; end
    rows = []; names = {}; pairs = [];
    for i = ports
        for j = ports
            if reflOnly && i ~= j, continue; end
            idx = (j-1)*4 + i;
            rows(end+1) = 2*idx-1;  %#ok<AGROW>  magnitude
            rows(end+1) = 2*idx;    %#ok<AGROW>  phase
            names{end+1} = sprintf('S%d%d', i, j);          %#ok<AGROW>
            pairs(end+1, :) = [2*idx-1, 2*idx];             %#ok<AGROW>
        end
    end
    [rows, ~] = sort(rows);
    names = unique(names, 'stable');
end

function S = buildSession(loaded, selRows, pairs, inputMode, nTdr)
% MATCHED-to-MLP feature construction. For a fair CNN-vs-MLP comparison every
% step here mirrors run_mlp_loso.py:
%   1. complex baseline subtraction   Y = S - S_baseline   (per S-param)
%   2. per-session mean subtraction   Y = Y - mean_samples(Y)
%   3. input representation (identical channel set to the MLP):
%        raw     : [mag; phase] per S-param
%        physics : [mag; phase; real; imag; IFFT/TDR(pad)] per S-param
%        tdr     : IFFT/TDR envelope per S-param
%   4. per-session z-score (per pixel, across this session's samples) -- the
%      MLP "KEY" trick, applied to train AND test sessions alike.
    data       = loaded.data;
    baseline   = loaded.baseline;
    nPos       = size(data, 1);
    trialCount = loaded.trialCount;
    nFreq      = loaded.numFreqPoints;
    K          = size(pairs, 1);

    % complex baseline per selected S-param (phase stored in DEGREES)
    baseC = zeros(K, nFreq);
    for k = 1:K
        baseC(k, :) = baseline(pairs(k,1), :) .* exp(1j * deg2rad(baseline(pairs(k,2), :)));
    end

    % ---- pass 1: calibrated complex Y per sample (Y = S - S_baseline) ----
    Yall = zeros(K, nFreq, nPos * trialCount);
    posLabel = cell(nPos * trialCount, 1);
    n = 0;
    for p = 1:nPos
        lbl = data{p, 1};
        for t = 1:trialCount
            raw = data{p, t+1};
            if isempty(raw) || any(isnan(raw(:))), continue; end
            n = n + 1;
            Sc = zeros(K, nFreq);
            for k = 1:K
                Sc(k, :) = raw(pairs(k,1), :) .* exp(1j * deg2rad(raw(pairs(k,2), :)));
            end
            Yall(:, :, n) = Sc - baseC;
            posLabel{n} = lbl;
        end
    end
    Yall = Yall(:, :, 1:n);
    posLabel = posLabel(1:n);

    % ---- step 2: per-session mean subtraction of complex Y (over samples) ----
    % (skippable ablation: CNN_LOSO_NO_MEANSUB=1 keeps only baseline subtraction)
    if ~strcmp(strtrim(getenv('CNN_LOSO_NO_MEANSUB')), '1')
        Yall = Yall - mean(Yall, 3);
    end

    % ---- step 3: build the requested representation ----
    switch inputMode
        case 'raw',     nRows = 2 * K; W = nFreq;
        case 'physics', nRows = 5 * K; W = nFreq;
        case 'tdr',     nRows = K;     W = nTdr;
        otherwise, error('unknown CNN_LOSO_INPUT %s', inputMode);
    end
    X = zeros(nRows, W, 1, n);
    for i = 1:n
        block = zeros(nRows, W);
        for k = 1:K
            yv = Yall(k, :, i);
            env = abs(ifft(yv));
            switch inputMode
                case 'raw'
                    block((k-1)*2 + (1:2), :) = [abs(yv); angle(yv)];
                case 'tdr'
                    block(k, :) = env(1:nTdr);
                case 'physics'
                    envpad = zeros(1, nFreq); envpad(1:nTdr) = env(1:nTdr);
                    block((k-1)*5 + (1:5), :) = [abs(yv); angle(yv); real(yv); imag(yv); envpad];
            end
        end
        X(:, :, 1, i) = block;
    end

    % ---- step 4: per-session z-score (per pixel, across samples) ----
    if n > 1
        X = (X - mean(X, 4)) ./ (std(X, 0, 4) + 1e-8);
    end

    S.X = X;
    S.posLabel = posLabel;
end

function [X, y] = gatherSamples(builtCells, validPos)
% Concatenate samples from a set of sessions, keeping only valid positions.
    Xs = {}; ys = {};
    for c = 1:numel(builtCells)
        B = builtCells{c};
        keep = ismember(B.posLabel, validPos);
        Xs{end+1} = B.X(:, :, :, keep); %#ok<AGROW>
        ys{end+1} = B.posLabel(keep);   %#ok<AGROW>
    end
    X = cat(4, Xs{:});
    y = vertcat(ys{:});
end

function q = quadOf(lbl, rowMid, colMid)
% RnCmPp label -> quadrant 1=TL 2=TR 3=BL 4=BR (split at rowMid/colMid).
    tok = regexp(lbl, 'R(\d+)C(\d+)', 'tokens');
    r = str2double(tok{1}{1}); c = str2double(tok{1}{2});
    if r <= rowMid && c <= colMid,      q = 1;
    elseif r <= rowMid && c >  colMid,  q = 2;
    elseif r >  rowMid && c <= colMid,  q = 3;
    else,                               q = 4;
    end
end

function predCell = predictHierCNN(XTrain, yTrain, XTest, quadTrain, nRows, nFreq, cfg, execEnv)
% Two-stage: Stage 1 predicts quadrant, Stage 2 predicts position within the
% predicted quadrant. Same CNN (trainCNN) at each stage.
    quads = unique(quadTrain);
    YQ = categorical(quadTrain);
    netQ = trainCNN(XTrain, YQ, nRows, nFreq, numel(quads), cfg, execEnv);
    predQ = str2double(string(classify(netQ, XTest)));    % predicted quadrant per test

    predCell = repmat({''}, size(XTest, 4), 1);
    for qi = 1:numel(quads)
        q = quads(qi);
        trMask = (quadTrain == q);
        teMask = (predQ == q);
        if ~any(teMask), continue; end
        posInQ = unique(yTrain(trMask));
        if numel(posInQ) == 1
            predCell(teMask) = posInQ(1); continue;
        end
        YqTrain = categorical(yTrain(trMask), posInQ);
        netP = trainCNN(XTrain(:,:,:,trMask), YqTrain, nRows, nFreq, numel(posInQ), cfg, execEnv);
        predP = classify(netP, XTest(:,:,:,teMask));
        predCell(teMask) = cellstr(predP);
    end
    % any test sample whose quadrant had no training positions -> first valid label
    empt = cellfun(@isempty, predCell);
    if any(empt), predCell(empt) = yTrain(1); end
end

function net = trainCNN(XTrain, YTrain, nRows, nFreq, nClasses, cfg, execEnv)
% The SAME single-stage CNN as Imager_ML_MultiSession.m (no leakage: the
% held-out session is never shown as validation data during LOSO training).
    layers = [
        imageInputLayer([nRows nFreq 1], 'Normalization', 'zscore', 'Name', 'input')
        convolution2dLayer([min(4,nRows) 20], cfg.Conv1, 'Padding', 'same', 'Name', 'conv1')
        batchNormalizationLayer('Name', 'bn1')
        reluLayer('Name', 'relu1')
        convolution2dLayer([min(2,nRows) 10], cfg.Conv2, 'Padding', 'same', 'Name', 'conv2')
        batchNormalizationLayer('Name', 'bn2')
        reluLayer('Name', 'relu2')
        fullyConnectedLayer(cfg.FC1, 'Name', 'fc1')
        batchNormalizationLayer('Name', 'bn3')
        reluLayer('Name', 'relu3')
        dropoutLayer(cfg.Dropout, 'Name', 'dropout')
        fullyConnectedLayer(nClasses, 'Name', 'fc_out')
        softmaxLayer('Name', 'softmax')
        classificationLayer('Name', 'output')
    ];

    if cfg.showPlots, plt = 'training-progress'; else, plt = 'none'; end
    opts = trainingOptions('adam', ...
        'MaxEpochs', cfg.Epochs, ...
        'MiniBatchSize', cfg.BatchSize, ...
        'InitialLearnRate', cfg.LR, ...
        'LearnRateSchedule', 'piecewise', ...
        'LearnRateDropPeriod', cfg.LRDropPeriod, ...
        'LearnRateDropFactor', cfg.LRDropFactor, ...
        'Shuffle', 'every-epoch', ...
        'ExecutionEnvironment', execEnv, ...
        'Verbose', false, ...
        'Plots', plt);

    net = trainNetwork(XTrain, YTrain, layers, opts);
end

function [posAcc, perPos] = perPositionVote(trueLbls, predLbls, validPos)
% Majority-vote each position's trials to a single predicted position.
    perPos = struct();
    correct = 0; total = 0;
    for p = 1:numel(validPos)
        lbl = validPos{p};
        mask = strcmp(trueLbls, lbl);
        if ~any(mask), continue; end
        votes = predLbls(mask);
        u = unique(votes);
        counts = cellfun(@(x) sum(strcmp(votes, x)), u);
        [~, wi] = max(counts);
        winner = u{wi};
        isCorrect = strcmp(winner, lbl);
        total = total + 1;
        correct = correct + isCorrect;
        fld = sprintf('pos_%d', p);
        perPos.(fld) = struct('label', lbl, 'correct', double(isCorrect));
    end
    posAcc = 0; if total > 0, posAcc = 100 * correct / total; end
end

function m = buildXYLookup(sessions)
% label -> [x y] inches, from the first session that has each label.
    m = containers.Map('KeyType', 'char', 'ValueType', 'any');
    for s = 1:numel(sessions)
        L = sessions{s}.posLabels;
        XY = sessions{s}.xyCoords;
        for i = 1:numel(L)
            if ~isKey(m, L{i})
                m(L{i}) = XY(i, :);
            end
        end
    end
end
