% =========================================================================
% AI ACKNOWLEDGMENT: This code was generated by Claude (Anthropic) with
% inputs and direction from Peter Martin.
%
% Imager_CNN_RegLOSO.m  --  Leave-One-Session-Out CNN (x,y) REGRESSION
%
% The regression counterpart to Imager_CNN_LOSO.m and the head-to-head twin
% of ../mlp_python/run_mlp_regloso.py.  Same conv trunk, same LOSO protocol,
% same preprocessing -- ONLY the head changes:
%
%     fc(nClasses) -> softmax -> classification      (classifier)
%     fc(2)        -> regression (MSE on x,y inches) (this file)
%
% PREPROCESSING = pipeline v2: complex baseline subtraction ONLY (no
% per-session mean subtraction).  Set CNN_LOSO_MEANSUB=1 to re-enable the
% v1 mean subtraction as an ablation.  Per-session z-score (the KEY trick)
% is unchanged.
%
% TARGETS: true physical (x, y) inches parsed from the RnCmPp labels --
%     cell centre  x = (col-0.5)*1.0,  y = (row-0.5)*1.0   (origin top-left)
%     sub-position +/-0.375 in  (P1 TL, P2 TR, P3 BR, P4 BL)
% with the photo-digitized overrides from position_adjustments.json applied
% where the glandular insert blocked the exact corner spot:
%     CNN_LOSO_ADJUST_KEY = A3_Empty | A3_F4 | A3_F5   (empty has none)
%
% METRICS (per fold + LOSO mean/std), mirroring run_mlp_regloso.py.
% Error DISTANCE only -- predictions are never snapped to grid positions:
%     trial-level    : mean/median Euclidean error (in), % <=0.5in / <=1in
%     position-level : median predicted point over a position's trials,
%                      then that point's error (majority-vote analog)
%     spread         : per-position mean radial distance of the trial
%                      predictions from their median (confidence proxy)
%     stratified     : near-insert (photo-adjusted labels) vs exterior,
%                      so insert-region error never pollutes exterior stats
%     centroid       : predict-the-train-centroid baseline
%
% ENV VARS (same driver pattern as Imager_CNN_LOSO.m):
%     CNN_LOSO_PARENT, CNN_LOSO_SESSIONS, CNN_LOSO_SETLABEL,
%     CNN_LOSO_ANT_MODE, CNN_LOSO_PORTS, CNN_LOSO_REFL_ONLY,
%     CNN_LOSO_INPUT, CNN_LOSO_PORT_REMAP, CNN_LOSO_EPOCHS,
%     CNN_LOSO_ADJUST_KEY (new), CNN_LOSO_MEANSUB (new, ablation)
%
% Outputs: ../results/cnn_regloso_<tag>.json (+ .mat, bar + spatial figures).
% The reg prefix keeps these out of the classification table/figure builders.
% =========================================================================

clear; clc; close all;

fprintf('=========================================================\n');
fprintf('  Imager CNN  --  LOSO (x,y) REGRESSION (Hunter 4-port)\n');
fprintf('=========================================================\n\n');

%% -----------------------------------------------------------------------
%  CONFIG  (same tunable CNN hyper-parameters as the classifier)
%  ----------------------------------------------------------------------
cfg.LR           = 1e-3;
cfg.BatchSize    = 16;
cfg.Epochs       = 100;
cfg.Conv1        = 32;
cfg.Conv2        = 32;
cfg.FC1          = 64;
cfg.Dropout      = 0.3;
cfg.LRDropFactor = 0.5;
cfg.LRDropPeriod = 30;
cfg.showPlots    = false;

if ~isempty(getenv('CNN_LOSO_EPOCHS'))
    cfg.Epochs = str2double(getenv('CNN_LOSO_EPOCHS'));
    fprintf('[override] Epochs = %d\n', cfg.Epochs);
end

rng(42);

if usejava('desktop'), figVis = 'on'; else, figVis = 'off'; end

LOADER_DIR = 'C:\Users\peter\Desktop\EM Imaging\Imager Program';
if exist(fullfile(LOADER_DIR, 'loadHunterVnaFolder.m'), 'file')
    addpath(LOADER_DIR);
else
    warning('loadHunterVnaFolder.m not found in %s.', LOADER_DIR);
end

thisDir = fileparts(mfilename('fullpath'));
if isempty(thisDir), thisDir = pwd; end
resultsDir = fullfile(fileparts(thisDir), 'results');
if ~isfolder(resultsDir), mkdir(resultsDir); end

%% -----------------------------------------------------------------------
%  1. SELECT DATA
%  ----------------------------------------------------------------------
defaultParent = ['C:\Users\peter\Desktop\EM Imaging\BreastPhantom\HunterVNA\' ...
                 'DataMeasurements\Sam Antennas\MediumAntenna\Separated\June18'];
if ~isfolder(defaultParent), defaultParent = pwd; end

if ~isempty(getenv('CNN_LOSO_PARENT'))
    parentDir = getenv('CNN_LOSO_PARENT');
    fprintf('[override] parent folder = %s\n', parentDir);
else
    fprintf('Select the PARENT folder that contains this setup''s session subfolders.\n');
    parentDir = uigetdir(defaultParent, 'Select parent folder (holds session subfolders)');
    if isequal(parentDir, 0)
        fprintf('Cancelled.\n'); return;
    end
end

[sessions, sessNames] = loadAllSessions(parentDir);
nSess = numel(sessions);
if nSess < 2
    error('LOSO needs at least 2 sessions; found %d in %s', nSess, parentDir);
end
fprintf('\nLoaded %d sessions:\n', nSess);
for s = 1:nSess
    fprintf('   [%d] %-45s  %d positions, %d trials\n', s, sessNames{s}, ...
        numel(sessions{s}.posLabels), sessions{s}.trialCount);
end

[~, setupName] = fileparts(parentDir);
if isempty(setupName), setupName = 'setup'; end

% v2 preprocessing is the DEFAULT; CNN_LOSO_MEANSUB=1 re-enables v1 mean sub.
meanSub = strcmp(strtrim(getenv('CNN_LOSO_MEANSUB')), '1');
setLabel = strtrim(getenv('CNN_LOSO_SETLABEL'));
if isempty(setLabel), setLabel = sprintf('%dsess', nSess); end
if meanSub
    setLabel = [setLabel '-meansub'];   % keep the v1 ablation outputs separate
    preproc = 'v1_session_mean';
else
    preproc = 'v2_no_session_mean';
end
fprintf('Session set: %s   preproc: %s\n', setLabel, preproc);

%% -----------------------------------------------------------------------
%  2. ANTENNA SUBSET + TARGET ADJUSTMENTS
%  ----------------------------------------------------------------------
reflOnly = strcmp(strtrim(getenv('CNN_LOSO_REFL_ONLY')), '1');
if ~isempty(getenv('CNN_LOSO_ANT_MODE'))
    antennaMode = lower(strtrim(getenv('CNN_LOSO_ANT_MODE')));
    ports = sort(unique(str2num(getenv('CNN_LOSO_PORTS')))); %#ok<ST2NM>
    if strcmp(antennaMode, 'all') || isempty(ports), ports = 1:4; antennaMode = 'all'; end
    if reflOnly, antennaMode = 'refl'; end
    fprintf('[override] antenna = %s  ports [%s]  reflOnly=%d\n', antennaMode, num2str(ports), reflOnly);
else
    antennaMode = 'all'; ports = 1:4;
    fprintf('No CNN_LOSO_ANT_MODE set -- defaulting to ALL antennas.\n');
end

[selRows, sparamNames, sparamPairs] = antennaRows(ports, reflOnly); %#ok<ASGLU>

inputMode = lower(strtrim(getenv('CNN_LOSO_INPUT')));
if isempty(inputMode), inputMode = 'raw'; end
N_TDR_BINS = 64;

% Photo-digitized true positions where the glandular insert blocked the
% exact corner (same file the spatial accuracy plots use).
adjKey = strtrim(getenv('CNN_LOSO_ADJUST_KEY'));
ADJ_JSON = ['C:\Users\peter\Desktop\EM Imaging\Research Paper\github_repo\' ...
            'detectable_change\A3_hunter\position_adjustments.json'];
adjMap = containers.Map('KeyType', 'char', 'ValueType', 'any');
if ~isempty(adjKey) && ~strcmpi(adjKey, 'none')
    if ~exist(ADJ_JSON, 'file')
        error('position_adjustments.json not found: %s', ADJ_JSON);
    end
    J = jsondecode(fileread(ADJ_JSON));
    if ~isfield(J, adjKey)
        error('adjust key "%s" not in %s (has: %s)', adjKey, ADJ_JSON, ...
              strjoin(fieldnames(J), ', '));
    end
    A = J.(adjKey);
    fn = fieldnames(A);
    for ii = 1:numel(fn)
        v = A.(fn{ii});
        adjMap(fn{ii}) = double(v(:)');
    end
    fprintf('Target adjustments [%s]: %d positions photo-corrected\n', adjKey, adjMap.Count);
else
    adjKey = 'none';
    fprintf('No target adjustments applied (CNN_LOSO_ADJUST_KEY unset/none).\n');
end

tag = sprintf('%s_%s_%s_%s_ant%s', matlab.lang.makeValidName(setupName), setLabel, ...
              inputMode, antennaMode, strrep(num2str(ports), '  ', '-'));
fprintf('Antenna mode: %s   ports [%s]   input=%s\n', upper(antennaMode), num2str(ports), inputMode);
fprintf('S-parameters used (%d): %s\n', numel(sparamNames), strjoin(sparamNames, ', '));

%% -----------------------------------------------------------------------
%  3. BUILD PER-SESSION SAMPLE TENSORS
%  ----------------------------------------------------------------------
fprintf('\n--- Building per-session samples ---\n');
built = cell(nSess, 1);
posSetPerSess = cell(nSess, 1);
for s = 1:nSess
    built{s} = buildSession(sessions{s}, sparamPairs, inputMode, N_TDR_BINS, meanSub);
    posSetPerSess{s} = unique(built{s}.posLabel);
    fprintf('   session %d: %d samples across %d positions\n', ...
        s, numel(built{s}.posLabel), numel(posSetPerSess{s}));
end

validPos = posSetPerSess{1};
for s = 2:nSess
    validPos = intersect(validPos, posSetPerSess{s});
end
validPos = sort(validPos);
nPos = numel(validPos);
if nPos < 2
    error('Fewer than 2 positions common to all sessions.');
end

% (x,y) inch target per valid position (canonical grid + photo overrides)
validXY = zeros(nPos, 2);
for p = 1:nPos
    validXY(p, :) = labelToXY(validPos{p}, adjMap);
end
% near-insert = the photo-adjusted labels (they hug the glandular insert)
nearInsert = arrayfun(@(p) isKey(adjMap, validPos{p}), (1:nPos)');
nAdjusted = sum(nearInsert);
fprintf('Common positions: %d   photo-adjusted (near-insert): %d\n', nPos, nAdjusted);

numSParamRows = size(built{1}.X, 1);
numFreqPoints = size(built{1}.X, 2);
fprintf('CNN input image: %d rows x %d cols  (input=%s)\n', numSParamRows, numFreqPoints, inputMode);

%% -----------------------------------------------------------------------
%  4. EXECUTION ENVIRONMENT
%  ----------------------------------------------------------------------
if strcmp(strtrim(getenv('CNN_LOSO_FORCE_CPU')), '1')
    execEnv = 'cpu';
    fprintf('\nCNN_LOSO_FORCE_CPU=1 -- training on CPU.\n');
elseif gpuDeviceCount > 0
    execEnv = 'gpu';
    fprintf('\nGPU detected (%s) -- training on GPU.\n', gpuDevice().Name);
else
    execEnv = 'cpu';
    fprintf('\nNo GPU -- training on CPU.\n');
end

%% -----------------------------------------------------------------------
%  5. LEAVE-ONE-SESSION-OUT LOOP
%  ----------------------------------------------------------------------
fprintf('\n=== %d-fold LEAVE-ONE-SESSION-OUT (regression) ===\n', nSess);
HALF_CELL_IN = 0.5;
folds = struct([]);
posErrAcc = zeros(nPos, nSess);   % per-fold median-point error per position
posSprAcc = zeros(nPos, nSess);   % per-fold prediction spread per position
posPredXAcc = nan(nPos, nSess);   % per-fold predicted median x per position
posPredYAcc = nan(nPos, nSess);   % per-fold predicted median y per position

for testS = 1:nSess
    trainS = setdiff(1:nSess, testS);
    t0 = tic;

    [XTrain, yTrain] = gatherSamples(built(trainS), validPos);
    [XTest,  yTest]  = gatherSamples(built(testS),  validPos);

    TTrain = labelsToXYMat(yTrain, adjMap);
    TTest  = labelsToXYMat(yTest,  adjMap);

    net = trainCNNReg(XTrain, TTrain, numSParamRows, numFreqPoints, cfg, execEnv);
    pred = double(predict(net, XTest));

    % ----- trial-level -----
    trialErr = vecnorm(pred - TTest, 2, 2);
    trial = errStats(trialErr, HALF_CELL_IN);

    % ----- position-level: median predicted point + prediction spread -----
    posErrs = nan(nPos, 1);
    posSprs = nan(nPos, 1);
    for p = 1:nPos
        mask = strcmp(yTest, validPos{p});
        if ~any(mask), continue; end
        P = pred(mask, :);
        med = median(P, 1);
        posErrs(p) = norm(med - validXY(p, :));
        posSprs(p) = mean(vecnorm(P - med, 2, 2));
        posErrAcc(p, testS) = posErrs(p);
        posSprAcc(p, testS) = posSprs(p);
        posPredXAcc(p, testS) = med(1); posPredYAcc(p, testS) = med(2);
    end
    have = ~isnan(posErrs);
    position = errStats(posErrs(have), HALF_CELL_IN);
    position.medianSpreadIn = median(posSprs(have));

    % ----- stratified: near-insert (photo-adjusted) vs exterior -----
    strat = struct();
    for g = 1:2
        if g == 1, sel = nearInsert & have; gname = 'nearInsert';
        else,      sel = ~nearInsert & have; gname = 'exterior'; end
        if any(sel)
            gs = errStats(posErrs(sel), HALF_CELL_IN);
            gs.medianSpreadIn = median(posSprs(sel));
            gs.n = sum(sel);
        else
            gs = struct('n', 0);
        end
        strat.(gname) = gs;
    end

    % ----- centroid baseline -----
    centroid = mean(TTrain, 1);
    baseErr = vecnorm(TTest - centroid, 2, 2);
    baseline = errStats(baseErr, HALF_CELL_IN);

    folds(testS).testSession      = sessNames{testS};
    folds(testS).trial            = trial;
    folds(testS).position         = position;
    folds(testS).stratified       = strat;
    folds(testS).baselineCentroid = baseline;

    if strat.nearInsert.n > 0
        niTxt = sprintf('near-insert med=%.3fin(n=%d)  ', ...
                        strat.nearInsert.medianErrIn, strat.nearInsert.n);
    else
        niTxt = '';
    end
    fprintf('  fold test=%d (%s):  trial med=%.3fin  pos med=%.3fin  <=0.5in %.0f%%  spread=%.3fin  %scentroid med=%.2fin  (%.1fs)\n', ...
        testS, sessNames{testS}, trial.medianErrIn, position.medianErrIn, ...
        position.pctWithinHalfIn, position.medianSpreadIn, niTxt, ...
        baseline.medianErrIn, toc(t0));
end

losoStat = @(fn) [mean(arrayfun(fn, folds)), std(arrayfun(fn, folds))];
losoPosMedianErr    = losoStat(@(f) f.position.medianErrIn);
losoPosMeanErr      = losoStat(@(f) f.position.meanErrIn);
losoPosPctHalfIn    = losoStat(@(f) f.position.pctWithinHalfIn);
losoPosPct1In       = losoStat(@(f) f.position.pctWithin1In);
losoPosMedianSpread = losoStat(@(f) f.position.medianSpreadIn);
losoTrialMedianErr  = losoStat(@(f) f.trial.medianErrIn);
losoTrialMeanErr    = losoStat(@(f) f.trial.meanErrIn);
losoCentroidMedian  = losoStat(@(f) f.baselineCentroid.medianErrIn);
losoNearInsertMedErr    = groupLoso(folds, 'nearInsert', 'medianErrIn');
losoNearInsertPctHalf   = groupLoso(folds, 'nearInsert', 'pctWithinHalfIn');
losoNearInsertMedSpread = groupLoso(folds, 'nearInsert', 'medianSpreadIn');
losoExteriorMedErr      = groupLoso(folds, 'exterior', 'medianErrIn');
losoExteriorPctHalf     = groupLoso(folds, 'exterior', 'pctWithinHalfIn');
losoExteriorMedSpread   = groupLoso(folds, 'exterior', 'medianSpreadIn');

fprintf('\n---------------------------------------------------------\n');
fprintf('  LOSO position median err : %.3f +/- %.3f in\n', losoPosMedianErr);
fprintf('  LOSO position <=0.5 in   : %.1f %%\n', losoPosPctHalfIn(1));
fprintf('  LOSO median spread       : %.3f in\n', losoPosMedianSpread(1));
if ~isnan(losoNearInsertMedErr(1))
    fprintf('  near-insert / exterior   : %.3f / %.3f in median\n', ...
        losoNearInsertMedErr(1), losoExteriorMedErr(1));
end
fprintf('  centroid baseline median : %.2f in\n', losoCentroidMedian(1));
fprintf('---------------------------------------------------------\n');

%% -----------------------------------------------------------------------
%  6. SAVE RESULTS (json + mat) and FIGURES
%  ----------------------------------------------------------------------
perPosition = struct('label', {}, 'x', {}, 'y', {}, 'predX', {}, 'predY', {}, ...
                     'medianErrIn', {}, 'spreadIn', {}, 'nearInsert', {});
for p = 1:nPos
    perPosition(end+1) = struct( ...
        'label', validPos{p}, ...
        'x', validXY(p, 1), 'y', validXY(p, 2), ...
        'predX', mean(posPredXAcc(p, :), 'omitnan'), ...
        'predY', mean(posPredYAcc(p, :), 'omitnan'), ...
        'medianErrIn', mean(posErrAcc(p, :)), ...
        'spreadIn', mean(posSprAcc(p, :)), ...
        'nearInsert', logical(nearInsert(p))); %#ok<SAGROW>
end

result = struct();
result.method             = 'CNN-REG';
result.task               = 'regression_xy_inches';
result.setup              = setupName;
result.sessionSet         = setLabel;
result.inputKind          = inputMode;
result.freqGrid           = 'native791';
result.preproc            = preproc;
result.adjustKey          = adjKey;
result.antennaMode        = antennaMode;
result.ports              = ports;
result.sparams            = {sparamNames{:}};
result.numRows            = numSParamRows;
result.numSessions        = nSess;
result.sessionNames       = {sessNames{:}};
result.numPositions       = nPos;
result.numAdjustedTargets = nAdjusted;
result.folds              = folds;
result.losoTrialMeanErr   = losoTrialMeanErr;
result.losoTrialMedianErr = losoTrialMedianErr;
result.losoPosMeanErr     = losoPosMeanErr;
result.losoPosMedianErr   = losoPosMedianErr;
result.losoPosPctHalfIn   = losoPosPctHalfIn;
result.losoPosPct1In      = losoPosPct1In;
result.losoPosMedianSpread = losoPosMedianSpread;
result.losoNearInsertMedianErr    = losoNearInsertMedErr;
result.losoNearInsertPctHalfIn    = losoNearInsertPctHalf;
result.losoNearInsertMedianSpread = losoNearInsertMedSpread;
result.losoExteriorMedianErr      = losoExteriorMedErr;
result.losoExteriorPctHalfIn      = losoExteriorPctHalf;
result.losoExteriorMedianSpread   = losoExteriorMedSpread;
result.losoCentroidMedianErr = losoCentroidMedian;
result.perPosition        = perPosition;
result.cnnConfig          = cfg;

jsonPath = fullfile(resultsDir, sprintf('cnn_regloso_%s.json', tag));
fid = fopen(jsonPath, 'w'); fprintf(fid, '%s', jsonencode(result, 'PrettyPrint', true)); fclose(fid);
fprintf('\nSaved %s\n', jsonPath);
save(fullfile(resultsDir, sprintf('cnn_regloso_%s.mat', tag)), 'result');

% ----- bar chart of per-fold median position error -----
figBar = figure('Name', 'CNN RegLOSO', 'Position', [100 100 900 480], 'Visible', figVis);
barVals = [arrayfun(@(f) f.position.medianErrIn, folds), losoPosMedianErr(1)];
barLbls = [arrayfun(@(k) sprintf('test=%d', k), 1:nSess, 'uni', 0), {'LOSO mean'}];
b = bar(barVals, 0.7); b.FaceColor = 'flat';
b.CData(1:nSess, :) = repmat([0.23 0.36 0.49], nSess, 1);
b.CData(end, :)     = [0.12 0.33 0.51];
hold on; yline(HALF_CELL_IN, '--k', 'half cell (0.5 in)');
for i = 1:numel(barVals)
    text(i, barVals(i) + 0.02, sprintf('%.2f', barVals(i)), 'HorizontalAlignment', 'center');
end
set(gca, 'XTick', 1:numel(barLbls), 'XTickLabel', barLbls);
ylabel('Median localization error (inches)');
title(sprintf('CNN RegLOSO  --  %s  --  %s (ports %s)', ...
    setupName, upper(antennaMode), num2str(ports)), 'Interpreter', 'none');
grid on;
saveas(figBar, fullfile(resultsDir, sprintf('cnn_regloso_%s_bars.png', tag)));

% ----- spatial map of per-position median error -----
figSp = figure('Name', 'CNN RegLOSO spatial', 'Position', [150 120 640 620], 'Visible', figVis);
xs = [perPosition.x]; ys = [perPosition.y]; errs = [perPosition.medianErrIn];
scatter(xs, ys, 260, errs, 'filled', 'MarkerEdgeColor', 'k'); hold on;
for i = 1:numel(errs)
    text(xs(i), ys(i), sprintf('%.1f', errs(i)), 'HorizontalAlignment', 'center', 'FontSize', 7);
end
colormap(gca, flipud(jet)); caxis([0 max(1.0, max(errs))]);
cb = colorbar; cb.Label.String = 'median localization error (in)';
set(gca, 'YDir', 'reverse'); axis equal; grid on;
xlabel('X (inches)'); ylabel('Y (inches)');
title(sprintf('Per-position localization error  --  median %.2f in', ...
    losoPosMedianErr(1)), 'Interpreter', 'none');
saveas(figSp, fullfile(resultsDir, sprintf('cnn_regloso_%s_spatial.png', tag)));

fprintf('Saved figures to %s\n', resultsDir);
fprintf('\nDone.  Compare against the MLP via ../mlp_python/run_mlp_regloso.py\n');


% =========================================================================
%  LOCAL FUNCTIONS
% =========================================================================
function [sessions, names] = loadAllSessions(parentDir)
% Enumerate Hunter session subfolders under parentDir and load each.
    d = dir(parentDir);
    subs = d([d.isdir] & ~ismember({d.name}, {'.', '..'}));
    filt = strtrim(getenv('CNN_LOSO_SESSIONS'));
    if ~isempty(filt)
        toks = strsplit(filt, {' ', ','});
        toks = toks(~cellfun(@isempty, toks));
        keep = false(1, numel(subs));
        for ii = 1:numel(subs)
            for tt = 1:numel(toks)
                if contains(subs(ii).name, toks{tt}), keep(ii) = true; break; end
            end
        end
        subs = subs(keep);
        fprintf('[filter] CNN_LOSO_SESSIONS=%s -> %d matching session folders\n', filt, numel(subs));
    end
    remapStr = strtrim(getenv('CNN_LOSO_PORT_REMAP'));
    rowperm = [];
    if ~isempty(remapStr)
        R = str2num(remapStr); %#ok<ST2NM>
        rowperm = zeros(1, 32);
        for a = 1:4
            for b = 1:4
                nidx = (b-1)*4 + a;  oidx = (R(b)-1)*4 + R(a);
                rowperm(2*nidx-1) = 2*oidx-1;  rowperm(2*nidx) = 2*oidx;
            end
        end
        fprintf('[remap] CNN_LOSO_PORT_REMAP=%s (new<-old ports)\n', remapStr);
    end

    sessions = {}; names = {};
    for i = 1:numel(subs)
        p = fullfile(parentDir, subs(i).name);
        if isHunterSession(p)
            fprintf('Loading session: %s\n', subs(i).name);
            try
                L = loadHunterVnaFolder(p);
                if ~isempty(rowperm)
                    L = permuteSessionRows(L, rowperm);
                end
                sessions{end+1} = L;             %#ok<AGROW>
                names{end+1}    = subs(i).name;  %#ok<AGROW>
            catch ME
                fprintf('  SKIP (%s)\n', ME.message);
            end
        end
    end
    if isempty(sessions) && isHunterSession(parentDir)
        error(['Selected folder is a single session. Select the PARENT ' ...
               'folder that contains multiple session subfolders.']);
    end
end

function tf = isHunterSession(p)
    tf = ~isempty(dir(fullfile(p, 'R*C*P*_T*.csv')));
end

function L = permuteSessionRows(L, rowperm)
% Reorder the 32 S-parameter rows of a loaded session by rowperm.
    for p = 1:size(L.data, 1)
        for t = 2:size(L.data, 2)
            M = L.data{p, t};
            if ~isempty(M) && size(M, 1) == numel(rowperm)
                L.data{p, t} = M(rowperm, :);
            end
        end
    end
    if isfield(L, 'baseline') && size(L.baseline, 1) == numel(rowperm)
        L.baseline = L.baseline(rowperm, :);
    end
    if isfield(L, 'baselineAll') && ~isempty(L.baselineAll) ...
            && size(L.baselineAll, 1) == numel(rowperm)
        L.baselineAll = L.baselineAll(rowperm, :, :);
    end
end

function [rows, names, pairs] = antennaRows(ports, reflOnly)
% Map an antenna (port) list to row indices in the 32-row Hunter matrix.
    if nargin < 2, reflOnly = false; end
    rows = []; names = {}; pairs = [];
    for i = ports
        for j = ports
            if reflOnly && i ~= j, continue; end
            idx = (j-1)*4 + i;
            rows(end+1) = 2*idx-1;  %#ok<AGROW>
            rows(end+1) = 2*idx;    %#ok<AGROW>
            names{end+1} = sprintf('S%d%d', i, j);          %#ok<AGROW>
            pairs(end+1, :) = [2*idx-1, 2*idx];             %#ok<AGROW>
        end
    end
    [rows, ~] = sort(rows);
    names = unique(names, 'stable');
end

function S = buildSession(loaded, pairs, inputMode, nTdr, meanSub)
% MATCHED-to-MLP feature construction (v2 default: NO session-mean sub).
%   1. complex baseline subtraction   Y = S - S_baseline
%   2. per-session mean subtraction   ONLY if meanSub (v1 ablation)
%   3. raw | physics | tdr representation (identical to run_mlp_regloso.py)
%   4. per-session z-score (per pixel, across samples) -- the KEY trick
    data       = loaded.data;
    baseline   = loaded.baseline;
    nPos       = size(data, 1);
    trialCount = loaded.trialCount;
    nFreq      = loaded.numFreqPoints;
    K          = size(pairs, 1);

    baseC = zeros(K, nFreq);
    for k = 1:K
        baseC(k, :) = baseline(pairs(k,1), :) .* exp(1j * deg2rad(baseline(pairs(k,2), :)));
    end

    Yall = zeros(K, nFreq, nPos * trialCount);
    posLabel = cell(nPos * trialCount, 1);
    n = 0;
    for p = 1:nPos
        lbl = data{p, 1};
        for t = 1:trialCount
            raw = data{p, t+1};
            if isempty(raw) || any(isnan(raw(:))), continue; end
            n = n + 1;
            Sc = zeros(K, nFreq);
            for k = 1:K
                Sc(k, :) = raw(pairs(k,1), :) .* exp(1j * deg2rad(raw(pairs(k,2), :)));
            end
            Yall(:, :, n) = Sc - baseC;
            posLabel{n} = lbl;
        end
    end
    Yall = Yall(:, :, 1:n);
    posLabel = posLabel(1:n);

    if meanSub
        Yall = Yall - mean(Yall, 3);   % v1 ablation only
    end

    switch inputMode
        case 'raw',     nRows = 2 * K; W = nFreq;
        case 'physics', nRows = 5 * K; W = nFreq;
        case 'tdr',     nRows = K;     W = nTdr;
        otherwise, error('unknown CNN_LOSO_INPUT %s', inputMode);
    end
    X = zeros(nRows, W, 1, n);
    for i = 1:n
        block = zeros(nRows, W);
        for k = 1:K
            yv = Yall(k, :, i);
            env = abs(ifft(yv));
            switch inputMode
                case 'raw'
                    block((k-1)*2 + (1:2), :) = [abs(yv); angle(yv)];
                case 'tdr'
                    block(k, :) = env(1:nTdr);
                case 'physics'
                    envpad = zeros(1, nFreq); envpad(1:nTdr) = env(1:nTdr);
                    block((k-1)*5 + (1:5), :) = [abs(yv); angle(yv); real(yv); imag(yv); envpad];
            end
        end
        X(:, :, 1, i) = block;
    end

    if n > 1
        X = (X - mean(X, 4)) ./ (std(X, 0, 4) + 1e-8);
    end

    S.X = X;
    S.posLabel = posLabel;
end

function [X, y] = gatherSamples(builtCells, validPos)
    Xs = {}; ys = {};
    for c = 1:numel(builtCells)
        B = builtCells{c};
        keep = ismember(B.posLabel, validPos);
        Xs{end+1} = B.X(:, :, :, keep); %#ok<AGROW>
        ys{end+1} = B.posLabel(keep);   %#ok<AGROW>
    end
    X = cat(4, Xs{:});
    y = vertcat(ys{:});
end

function xy = labelToXY(lbl, adjMap)
% Canonical RnCmPp -> (x, y) inches (matches label_xy.py exactly), with
% photo-digitized overrides taking precedence.
    if isKey(adjMap, lbl)
        xy = adjMap(lbl); return;
    end
    tok = regexp(lbl, 'R(\d+)C(\d+)P(\d+)', 'tokens'); t = tok{1};
    r = str2double(t{1}); c = str2double(t{2}); p = str2double(t{3});
    sp = 0.375;                       % 0.5 half-cell - 0.125 half-divider
    off = [-sp -sp; +sp -sp; +sp +sp; -sp +sp];   % P1 TL, P2 TR, P3 BR, P4 BL
    xy = [(c - 0.5) + off(p, 1), (r - 0.5) + off(p, 2)];
end

function T = labelsToXYMat(labels, adjMap)
    T = zeros(numel(labels), 2);
    for i = 1:numel(labels)
        T(i, :) = labelToXY(labels{i}, adjMap);
    end
end

function M = errStats(err, halfCell)
    M.meanErrIn       = mean(err);
    M.medianErrIn     = median(err);
    M.pctWithinHalfIn = 100 * mean(err <= halfCell);
    M.pctWithin1In    = 100 * mean(err <= 1.0);
end

function v = groupLoso(folds, gname, field)
% [mean std] of a stratified-group stat across folds where the group is
% non-empty; [NaN NaN] if the group never appears (e.g. empty phantom).
    vals = [];
    for i = 1:numel(folds)
        g = folds(i).stratified.(gname);
        if isfield(g, 'n') && g.n > 0
            vals(end+1) = g.(field); %#ok<AGROW>
        end
    end
    if isempty(vals), v = [NaN NaN]; else, v = [mean(vals), std(vals)]; end
end

function net = trainCNNReg(XTrain, TTrain, nRows, nFreq, cfg, execEnv)
% SAME conv trunk as Imager_CNN_LOSO.m; head = fc(2) + regression (MSE on
% x,y inches).  No leakage: held-out session never seen during training.
    layers = [
        imageInputLayer([nRows nFreq 1], 'Normalization', 'zscore', 'Name', 'input')
        convolution2dLayer([min(4,nRows) 20], cfg.Conv1, 'Padding', 'same', 'Name', 'conv1')
        batchNormalizationLayer('Name', 'bn1')
        reluLayer('Name', 'relu1')
        convolution2dLayer([min(2,nRows) 10], cfg.Conv2, 'Padding', 'same', 'Name', 'conv2')
        batchNormalizationLayer('Name', 'bn2')
        reluLayer('Name', 'relu2')
        fullyConnectedLayer(cfg.FC1, 'Name', 'fc1')
        batchNormalizationLayer('Name', 'bn3')
        reluLayer('Name', 'relu3')
        dropoutLayer(cfg.Dropout, 'Name', 'dropout')
        fullyConnectedLayer(2, 'Name', 'fc_out')
        regressionLayer('Name', 'output')
    ];

    if cfg.showPlots, plt = 'training-progress'; else, plt = 'none'; end
    opts = trainingOptions('adam', ...
        'MaxEpochs', cfg.Epochs, ...
        'MiniBatchSize', cfg.BatchSize, ...
        'InitialLearnRate', cfg.LR, ...
        'LearnRateSchedule', 'piecewise', ...
        'LearnRateDropPeriod', cfg.LRDropPeriod, ...
        'LearnRateDropFactor', cfg.LRDropFactor, ...
        'Shuffle', 'every-epoch', ...
        'ExecutionEnvironment', execEnv, ...
        'Verbose', false, ...
        'Plots', plt);

    net = trainNetwork(XTrain, TTrain, layers, opts);
end
