% =========================================================================
% AI ACKNOWLEDGMENT: This code was generated by Claude (Anthropic) with
% inputs and direction from Peter Martin.
%
% Imager_CNN_RegLOPO.m  --  Leave-One-POSITION-Out (x,y) REGRESSION CNN
%
% A DIFFERENT cross-validation from Imager_CNN_RegLOSO.m.  Instead of holding
% out a whole recording SESSION, this holds out a GRID POSITION the model has
% never seen a signature for, and asks it to predict that position's (x,y).
% This tests SPATIAL INTERPOLATION of the field -- something the classifiers
% structurally could not do (a zero-example class can never be predicted).
%
% TWO MODES  (env LOPO_MODE):
%   insession : train + test within ONE session, rotated over sessions.
%               Session drift is removed -> pure interpolation question.
%   pooled    : hold the position out of EVERY session; train on all remaining
%               positions from all sessions.  Tests interpolation AND
%               cross-session generalization at once (closest to deployment).
%
% TWO GRANULARITIES  (env LOPO_UNIT):
%   subpos : hold out ONE sub-position (its 3 cell-mates ~0.75in away stay in
%            training) -> gentle interpolation.
%   cell   : hold out the WHOLE cell (all 4 sub-positions) -> forces bridging
%            a full inch-plus gap -> strong test of learned spatial structure.
%
% This is DISTINCT from LOSO and the two modes/granularities are DISTINCT from
% each other, in both the console banner and the output filenames:
%     cnn_reglopo_<mode>_<unit>_<setup>_<setlabel>_<input>.json
% (LOSO writes cnn_regloso_*, so the two families never collide.)
%
% Same data pipeline as RegLOSO: complex baseline subtraction (v2, no session-
% mean), raw|physics|tdr features, per-session z-score, conv trunk + fc(2) +
% regressionLayer.  Error DISTANCE only (no snapping).  Targets = canonical
% grid (x,y) + photo overrides (CNN_LOSO_ADJUST_KEY).
%
% ENV VARS: CNN_LOSO_PARENT, CNN_LOSO_SESSIONS, CNN_LOSO_PORT_REMAP,
%   CNN_LOSO_ADJUST_KEY, CNN_LOSO_INPUT (default raw), CNN_LOSO_MEANSUB,
%   CNN_LOSO_EPOCHS (default 40 here -- LOPO trains many folds),
%   CNN_LOSO_SETLABEL, LOPO_MODE (insession|pooled), LOPO_UNIT (subpos|cell).
% =========================================================================

clear; clc; close all;

fprintf('==============================================================\n');
fprintf('  Imager CNN  --  Leave-One-POSITION-Out (x,y) REGRESSION\n');
fprintf('==============================================================\n\n');

%% CONFIG
cfg.LR = 1e-3; cfg.BatchSize = 16; cfg.Epochs = 40;
cfg.Conv1 = 32; cfg.Conv2 = 32; cfg.FC1 = 64; cfg.Dropout = 0.3;
cfg.LRDropFactor = 0.5; cfg.LRDropPeriod = 30; cfg.showPlots = false;
if ~isempty(getenv('CNN_LOSO_EPOCHS'))
    cfg.Epochs = str2double(getenv('CNN_LOSO_EPOCHS'));
    fprintf('[override] Epochs = %d\n', cfg.Epochs);
end
rng(42);
if usejava('desktop'), figVis = 'on'; else, figVis = 'off'; end

LOADER_DIR = 'C:\Users\peter\Desktop\EM Imaging\Imager Program';
if exist(fullfile(LOADER_DIR, 'loadHunterVnaFolder.m'), 'file'), addpath(LOADER_DIR); end
thisDir = fileparts(mfilename('fullpath')); if isempty(thisDir), thisDir = pwd; end
resultsDir = fullfile(fileparts(thisDir), 'results');
if ~isfolder(resultsDir), mkdir(resultsDir); end

% ---- LOPO mode + granularity ----
lopoMode = lower(strtrim(getenv('LOPO_MODE'))); if isempty(lopoMode), lopoMode = 'pooled'; end
lopoUnit = lower(strtrim(getenv('LOPO_UNIT'))); if isempty(lopoUnit), lopoUnit = 'cell'; end
if ~ismember(lopoMode, {'insession', 'pooled'}), error('LOPO_MODE must be insession|pooled'); end
if ~ismember(lopoUnit, {'subpos', 'cell'}), error('LOPO_UNIT must be subpos|cell'); end
fprintf('LOPO mode = %s   granularity = %s\n', upper(lopoMode), upper(lopoUnit));

% ---- Experiment 1: mixup augmentation (off unless MIXUP_ALPHA>0) ----
% Offline mixup for regression: append synthetic TRAIN samples that are convex
% blends of random training pairs, with matching convex-blended (x,y) targets.
% Teaches the signal->coordinate map to be smooth -> better interpolation to
% never-seen positions. Applied to TRAIN only, never the held-out cell.
mixAlpha = str2double(getenv('MIXUP_ALPHA')); if isnan(mixAlpha), mixAlpha = 0; end
mixRatio = str2double(getenv('MIXUP_RATIO')); if isnan(mixRatio), mixRatio = 1.0; end
if mixAlpha > 0
    fprintf('MIXUP ON: alpha=%.2f  ratio=%.2f  (blend train pairs + their xy)\n', mixAlpha, mixRatio);
end

% ---- Experiment 2: position-disjoint validation (off unless POSVAL_FRAC>0) ----
% Carve a fraction of the TRAIN positions out as a validation set (all their
% trials, none in training) and keep the network with the best validation loss
% (OutputNetwork='best-validation'). Selects for generalization to UNSEEN
% positions rather than long training on memorized ones.
posValFrac = str2double(getenv('POSVAL_FRAC')); if isnan(posValFrac), posValFrac = 0; end
if posValFrac > 0
    fprintf('POSVAL ON: frac=%.2f of train positions held out for best-net selection\n', posValFrac);
end

% ---- Experiment 3: structured (heatmap) output (HEAD_MODE=heatmap) ----
% Instead of fc(2) regressing bare (x,y), output a softmax over a grid of
% coordinate anchors, trained against a Gaussian blob centred at the true xy,
% and read out the prediction as the distribution's centroid. Neighbouring
% positions share output support -> smoother interpolation. Uses only built-in
% layers (fc -> softmax -> regression on the soft target).
headMode = lower(strtrim(getenv('HEAD_MODE'))); if isempty(headMode), headMode = 'xy'; end
if ~ismember(headMode, {'xy', 'heatmap'}), error('HEAD_MODE must be xy|heatmap'); end
hmSigma = str2double(getenv('HEATMAP_SIGMA')); if isnan(hmSigma), hmSigma = 0.6; end
if strcmp(headMode, 'heatmap')
    fprintf('HEAD=heatmap  sigma=%.2f in  (soft-argmax centroid readout)\n', hmSigma);
end

%% 1. DATA
defaultParent = ['C:\Users\peter\Desktop\EM Imaging\BreastPhantom\HunterVNA\' ...
                 'DataMeasurements\Sam Antennas\MediumAntenna\Separated\June18'];
if ~isfolder(defaultParent), defaultParent = pwd; end
if ~isempty(getenv('CNN_LOSO_PARENT'))
    parentDir = getenv('CNN_LOSO_PARENT');
    fprintf('[override] parent folder = %s\n', parentDir);
else
    parentDir = uigetdir(defaultParent, 'Select parent folder (holds session subfolders)');
    if isequal(parentDir, 0), fprintf('Cancelled.\n'); return; end
end

[sessions, sessNames] = loadAllSessions(parentDir);
nSess = numel(sessions);
if nSess < 1, error('No sessions found in %s', parentDir); end
if strcmp(lopoMode, 'pooled') && nSess < 2
    fprintf('[note] pooled LOPO with 1 session == insession LOPO.\n');
end
fprintf('\nLoaded %d sessions:\n', nSess);
for s = 1:nSess
    fprintf('   [%d] %-45s  %d positions, %d trials\n', s, sessNames{s}, ...
        numel(sessions{s}.posLabels), sessions{s}.trialCount);
end
[~, setupName] = fileparts(parentDir); if isempty(setupName), setupName = 'setup'; end
meanSub = strcmp(strtrim(getenv('CNN_LOSO_MEANSUB')), '1');
if meanSub, preproc = 'v1_session_mean'; else, preproc = 'v2_no_session_mean'; end
setLabel = strtrim(getenv('CNN_LOSO_SETLABEL'));
if isempty(setLabel), setLabel = sprintf('%dsess', nSess); end
if meanSub, setLabel = [setLabel '-meansub']; end
if mixAlpha > 0, setLabel = [setLabel sprintf('-mixup%s', strrep(num2str(mixAlpha), '.', 'p'))]; end
if posValFrac > 0, setLabel = [setLabel sprintf('-posval%s', strrep(num2str(posValFrac), '.', 'p'))]; end
if strcmp(headMode, 'heatmap'), setLabel = [setLabel sprintf('-heatmap%s', strrep(num2str(hmSigma), '.', 'p'))]; end

%% 2. ANTENNAS + TARGETS
ports = 1:4; antennaMode = 'all';   % first pass: full 4-antenna array only
[selRows, sparamNames, sparamPairs] = antennaRows(ports, false); %#ok<ASGLU>
inputMode = lower(strtrim(getenv('CNN_LOSO_INPUT'))); if isempty(inputMode), inputMode = 'raw'; end
N_TDR_BINS = 64;

adjKey = strtrim(getenv('CNN_LOSO_ADJUST_KEY'));
ADJ_JSON = ['C:\Users\peter\Desktop\EM Imaging\Research Paper\github_repo\' ...
            'detectable_change\A3_hunter\position_adjustments.json'];
adjMap = containers.Map('KeyType', 'char', 'ValueType', 'any');
if ~isempty(adjKey) && ~strcmpi(adjKey, 'none')
    J = jsondecode(fileread(ADJ_JSON));
    if ~isfield(J, adjKey), error('adjust key "%s" not in %s', adjKey, ADJ_JSON); end
    A = J.(adjKey); fn = fieldnames(A);
    for ii = 1:numel(fn), v = A.(fn{ii}); adjMap(fn{ii}) = double(v(:)'); end
    fprintf('Target adjustments [%s]: %d positions photo-corrected\n', adjKey, adjMap.Count);
else
    adjKey = 'none';
end

tag = sprintf('%s_%s_%s_%s_%s', lopoMode, lopoUnit, ...
              matlab.lang.makeValidName(setupName), setLabel, inputMode);
fprintf('Input=%s  antenna=ALL(16 S-params)  preproc=%s  adjust=%s\n', inputMode, preproc, adjKey);

%% 3. BUILD PER-SESSION TENSORS
fprintf('\n--- Building per-session samples ---\n');
built = cell(nSess, 1); posSetPerSess = cell(nSess, 1);
for s = 1:nSess
    built{s} = buildSession(sessions{s}, sparamPairs, inputMode, N_TDR_BINS, meanSub);
    posSetPerSess{s} = unique(built{s}.posLabel);
    fprintf('   session %d: %d samples across %d positions\n', ...
        s, numel(built{s}.posLabel), numel(posSetPerSess{s}));
end
validPos = posSetPerSess{1};
for s = 2:nSess, validPos = intersect(validPos, posSetPerSess{s}); end
validPos = sort(validPos); nPos = numel(validPos);
if nPos < 3, error('Need >=3 common positions for LOPO.'); end

validXY = zeros(nPos, 2);
for p = 1:nPos, validXY(p, :) = labelToXY(validPos{p}, adjMap); end
xyOf = containers.Map(validPos, num2cell(validXY, 2)');

% heatmap anchor grid (only used if headMode=heatmap): regular 0.4-in lattice
% covering the target extent + margin, so the centroid readout can reach every
% true position.
axStep = 0.4; axPad = 0.6;
ax = (min(validXY(:,1)) - axPad) : axStep : (max(validXY(:,1)) + axPad);
ay = (min(validXY(:,2)) - axPad) : axStep : (max(validXY(:,2)) + axPad);
[AX, AY] = meshgrid(ax, ay);
anchors = [AX(:), AY(:)];
if strcmp(headMode, 'heatmap')
    fprintf('Heatmap anchors: %d (%.1f-in grid over [%.1f,%.1f]x[%.1f,%.1f])\n', ...
        size(anchors,1), axStep, ax(1), ax(end), ay(1), ay(end));
end
nearInsertMap = containers.Map(validPos, num2cell(arrayfun(@(p) isKey(adjMap, validPos{p}), 1:nPos)));

% ---- define held-out units ----
if strcmp(lopoUnit, 'subpos')
    units = cellfun(@(L) {L}, validPos, 'uni', 0);      % one label each
    unitName = validPos;
else  % cell: group by RxCy
    ckey = cellfun(@(L) regexprep(L, 'P\d+$', ''), validPos, 'uni', 0);
    unitName = unique(ckey, 'stable');
    units = cell(numel(unitName), 1);
    for i = 1:numel(unitName), units{i} = validPos(strcmp(ckey, unitName{i})); end
end
nUnits = numel(units);
fprintf('Common positions: %d   held-out units (%s): %d\n', nPos, lopoUnit, nUnits);

numSParamRows = size(built{1}.X, 1); numFreqPoints = size(built{1}.X, 2);
if gpuDeviceCount > 0, execEnv = 'gpu'; else, execEnv = 'cpu'; end
fprintf('CNN input: %d x %d  (input=%s)   env=%s\n', numSParamRows, numFreqPoints, inputMode, execEnv);

%% 4. LOPO LOOP  -> collect one record per held-out position (per context)
HALF = 0.5;
rec = struct('label', {}, 'sess', {}, 'err', {}, 'spread', {}, 'near', {});
nFoldTotal = 0; tAll = tic;

if strcmp(lopoMode, 'pooled')
    % pool all valid samples across sessions once
    Xp = []; yp = {};
    for s = 1:nSess
        keep = ismember(built{s}.posLabel, validPos);
        Xp = cat(4, Xp, built{s}.X(:, :, :, keep));
        yp = [yp; built{s}.posLabel(keep)]; %#ok<AGROW>
    end
    for u = 1:nUnits
        t0 = tic;
        teMask = ismember(yp, units{u}); trMask = ~teMask;
        yTr = yp(trMask);
        TTr = labelsToXY(yTr, adjMap);
        [Xt0, Tt0, Xv0, Tv0] = posDisjointSplit(Xp(:, :, :, trMask), TTr, yTr, posValFrac);
        [Xtr_a, Ttr_a] = maybeMixup(Xt0, Tt0, mixAlpha, mixRatio);
        predTe = fitPredictFold(Xtr_a, Ttr_a, Xp(:, :, :, teMask), Xv0, Tv0, ...
                                headMode, anchors, hmSigma, numSParamRows, numFreqPoints, cfg, execEnv);
        yTe = yp(teMask);
        rec = accumUnit(rec, units{u}, yTe, predTe, xyOf, nearInsertMap, '(pooled)');
        nFoldTotal = nFoldTotal + 1;
        fprintf('  [%s %s] unit %d/%d = %s  (%d test pos, %.1fs)\n', ...
            lopoMode, lopoUnit, u, nUnits, unitName{u}, numel(units{u}), toc(t0));
    end
else  % insession
    for s = 1:nSess
        keep = ismember(built{s}.posLabel, validPos);
        Xs = built{s}.X(:, :, :, keep); ys = built{s}.posLabel(keep);
        for u = 1:nUnits
            teMask = ismember(ys, units{u}); if ~any(teMask), continue; end
            t0 = tic;
            trMask = ~teMask; yTr = ys(trMask);
            TTr = labelsToXY(yTr, adjMap);
            [Xt0, Tt0, Xv0, Tv0] = posDisjointSplit(Xs(:, :, :, trMask), TTr, yTr, posValFrac);
            [Xtr_a, Ttr_a] = maybeMixup(Xt0, Tt0, mixAlpha, mixRatio);
            predTe = fitPredictFold(Xtr_a, Ttr_a, Xs(:, :, :, teMask), Xv0, Tv0, ...
                                    headMode, anchors, hmSigma, numSParamRows, numFreqPoints, cfg, execEnv);
            rec = accumUnit(rec, units{u}, ys(teMask), predTe, xyOf, nearInsertMap, sessNames{s});
            nFoldTotal = nFoldTotal + 1;
            if mod(u, 5) == 0 || u == nUnits
                fprintf('  [%s %s] sess %d/%d unit %d/%d  (%.1fs, %.0fs elapsed)\n', ...
                    lopoMode, lopoUnit, s, nSess, u, nUnits, toc(t0), toc(tAll));
            end
        end
    end
end
fprintf('LOPO done: %d folds in %.0f s\n', nFoldTotal, toc(tAll));

%% 5. AGGREGATE (error distance only)
errs = [rec.err]; sprs = [rec.spread]; near = logical([rec.near]);
overall = distStats(errs, sprs, HALF);
stratN = distStats(errs(near), sprs(near), HALF);
stratE = distStats(errs(~near), sprs(~near), HALF);

% per-session summary (meaningful for insession; single pass for pooled)
usess = unique({rec.sess}, 'stable');
perSession = struct('sess', {}, 'medianErrIn', {}, 'pctWithinHalfIn', {}, 'medianSpreadIn', {}, 'n', {});
for i = 1:numel(usess)
    m = strcmp({rec.sess}, usess{i});
    ss = distStats([rec(m).err], [rec(m).spread], HALF);
    perSession(end+1) = struct('sess', usess{i}, 'medianErrIn', ss.medianErrIn, ...
        'pctWithinHalfIn', ss.pctWithinHalfIn, 'medianSpreadIn', ss.medianSpreadIn, ...
        'n', numel([rec(m).err])); %#ok<SAGROW>
end
if numel(perSession) > 1
    crossMedErr = [mean([perSession.medianErrIn]), std([perSession.medianErrIn])];
    crossPctHalf = [mean([perSession.pctWithinHalfIn]), std([perSession.pctWithinHalfIn])];
else
    crossMedErr = [overall.medianErrIn, 0]; crossPctHalf = [overall.pctWithinHalfIn, 0];
end

% per-position (average a position's records across contexts)
perPosition = struct('label', {}, 'x', {}, 'y', {}, 'medianErrIn', {}, 'spreadIn', {}, 'nearInsert', {});
for p = 1:nPos
    m = strcmp({rec.label}, validPos{p});
    if ~any(m), continue; end
    perPosition(end+1) = struct('label', validPos{p}, 'x', validXY(p, 1), 'y', validXY(p, 2), ...
        'medianErrIn', mean([rec(m).err]), 'spreadIn', mean([rec(m).spread]), ...
        'nearInsert', logical(nearInsertMap(validPos{p}))); %#ok<SAGROW>
end

fprintf('\n--------------------------------------------------------------\n');
fprintf('  %s / %s   %s [%s]\n', upper(lopoMode), upper(lopoUnit), setupName, setLabel);
fprintf('  LOPO position median err : %.3f in   (mean %.3f)\n', overall.medianErrIn, overall.meanErrIn);
fprintf('  LOPO position <=0.5 in   : %.1f %%   (<=1in %.1f%%)\n', overall.pctWithinHalfIn, overall.pctWithin1In);
fprintf('  median spread            : %.3f in\n', overall.medianSpreadIn);
if stratN.n > 0
    fprintf('  near-insert / exterior   : %.3f / %.3f in median (n=%d/%d)\n', ...
        stratN.medianErrIn, stratE.medianErrIn, stratN.n, stratE.n);
end
if numel(perSession) > 1
    fprintf('  per-session median err   : %.3f +/- %.3f in (across %d sessions)\n', ...
        crossMedErr(1), crossMedErr(2), numel(perSession));
end
fprintf('--------------------------------------------------------------\n');

%% 6. SAVE
result = struct();
result.method = 'CNN-LOPO'; result.task = 'regression_xy_inches';
result.lopoMode = lopoMode; result.lopoUnit = lopoUnit;
result.setup = setupName; result.sessionSet = setLabel;
result.inputKind = inputMode; result.preproc = preproc; result.adjustKey = adjKey;
result.antennaMode = antennaMode; result.ports = ports;
result.numSessions = nSess; result.sessionNames = {sessNames{:}};
result.numPositions = nPos; result.numUnits = nUnits; result.numFolds = nFoldTotal;
result.epochs = cfg.Epochs;
result.mixupAlpha = mixAlpha; result.mixupRatio = mixRatio;
result.posValFrac = posValFrac;
result.headMode = headMode; result.heatmapSigma = hmSigma;
if strcmp(headMode, 'heatmap'), result.numAnchors = size(anchors, 1); end
result.overall = overall;
result.nearInsert = stratN; result.exterior = stratE;
result.crossContextMedianErr = crossMedErr; result.crossContextPctHalfIn = crossPctHalf;
result.perSession = perSession;
result.perPosition = perPosition;
result.cnnConfig = cfg;

jsonPath = fullfile(resultsDir, sprintf('cnn_reglopo_%s.json', tag));
fid = fopen(jsonPath, 'w'); fprintf(fid, '%s', jsonencode(result, 'PrettyPrint', true)); fclose(fid);
fprintf('\nSaved %s\n', jsonPath);
save(fullfile(resultsDir, sprintf('cnn_reglopo_%s.mat', tag)), 'result');

% spatial error map
figSp = figure('Name', 'CNN LOPO spatial', 'Position', [150 120 640 620], 'Visible', figVis);
xs = [perPosition.x]; ys = [perPosition.y]; ee = [perPosition.medianErrIn];
scatter(xs, ys, 260, ee, 'filled', 'MarkerEdgeColor', 'k'); hold on;
for i = 1:numel(ee), text(xs(i), ys(i), sprintf('%.1f', ee(i)), 'HorizontalAlignment', 'center', 'FontSize', 7); end
colormap(gca, flipud(jet)); caxis([0 max(1.0, max(ee))]);
cb = colorbar; cb.Label.String = 'LOPO median error (in)';
set(gca, 'YDir', 'reverse'); axis equal; grid on;
xlabel('X (in)'); ylabel('Y (in)');
title(sprintf('%s/%s LOPO  --  %s  --  median %.2f in', ...
    upper(lopoMode), upper(lopoUnit), setupName, overall.medianErrIn), 'Interpreter', 'none');
saveas(figSp, fullfile(resultsDir, sprintf('cnn_reglopo_%s_spatial.png', tag)));
fprintf('Saved figure.\nDone.\n');


% =========================================================================
%  LOCAL FUNCTIONS
% =========================================================================
function rec = accumUnit(rec, unitLabels, yTe, predTe, xyOf, nearMap, sessTag)
% For each position in the held-out unit: median predicted point over its
% trials, error to the true (x,y), and prediction spread. Append to rec.
    for q = 1:numel(unitLabels)
        L = unitLabels{q};
        m = strcmp(yTe, L); if ~any(m), continue; end
        P = predTe(m, :); med = median(P, 1);
        xy = xyOf(L);
        rec(end+1) = struct('label', L, 'sess', sessTag, ...
            'err', norm(med - xy), ...
            'spread', mean(vecnorm(P - med, 2, 2)), ...
            'near', double(nearMap(L))); %#ok<AGROW>
    end
end

function [Xo, To] = maybeMixup(X, T, alpha, ratio)
% Offline mixup for regression. Appends `ratio*N` synthetic samples, each a
% convex blend  l*A + (1-l)*B  of a random training pair, with the SAME blend
% applied to their (x,y) targets. l ~ Beta(alpha,alpha). Train-only; no test
% data is ever touched, so there is no LOPO leakage.
    if alpha <= 0 || ratio <= 0, Xo = X; To = T; return; end
    n = size(X, 4);
    if n < 2, Xo = X; To = T; return; end
    nMix = max(1, round(ratio * n));
    ii = randi(n, nMix, 1); jj = randi(n, nMix, 1);
    if exist('betarnd', 'file'), lam = betarnd(alpha, alpha, nMix, 1);
    else, lam = rand(nMix, 1); end                 % Beta(1,1) fallback
    sz = size(X);
    Xmix = zeros([sz(1), sz(2), 1, nMix], 'like', X);
    Tmix = zeros(nMix, size(T, 2));
    for k = 1:nMix
        l = lam(k);
        Xmix(:, :, 1, k) = l * X(:, :, 1, ii(k)) + (1 - l) * X(:, :, 1, jj(k));
        Tmix(k, :)       = l * T(ii(k), :)       + (1 - l) * T(jj(k), :);
    end
    Xo = cat(4, X, Xmix); To = [T; Tmix];
end

function predTe = fitPredictFold(Xtr, xyTr, Xte, Xval, xyVal, headMode, anchors, hmSigma, nRows, nFreq, cfg, execEnv)
% Train one fold and return predicted (x,y) for the test samples. Dispatches on
% head: 'xy' = fc(2)+regression; 'heatmap' = softmax over anchor grid trained on
% a Gaussian soft target, prediction = distribution centroid.
    if strcmp(headMode, 'heatmap')
        TsoftTr = xyToHeatmap(xyTr, anchors, hmSigma);
        if ~isempty(Xval), TsoftV = xyToHeatmap(xyVal, anchors, hmSigma); else, TsoftV = []; end
        net = trainCNNHeatmap(Xtr, TsoftTr, nRows, nFreq, size(anchors,1), cfg, execEnv, Xval, TsoftV);
        soft = double(predict(net, Xte));        % (Nte x G) softmax over anchors
        predTe = soft * anchors;                 % centroid readout -> (Nte x 2)
    else
        net = trainCNNReg(Xtr, xyTr, nRows, nFreq, cfg, execEnv, Xval, xyVal);
        predTe = double(predict(net, Xte));
    end
end

function P = xyToHeatmap(xy, anchors, sigma)
% Soft target: each sample -> Gaussian over the anchor grid, normalized to a
% probability vector. (N x G)
    n = size(xy, 1); G = size(anchors, 1);
    P = zeros(n, G);
    for i = 1:n
        d2 = sum((anchors - xy(i, :)).^2, 2);
        w = exp(-d2 / (2 * sigma^2));
        s = sum(w); if s <= 0, w = ones(G,1); s = G; end
        P(i, :) = (w / s)';
    end
end

function net = trainCNNHeatmap(XTrain, Tsoft, nRows, nFreq, G, cfg, execEnv, Xval, Tval)
% Same conv trunk as trainCNNReg but head = fc(G) -> softmax -> regression on
% the soft (Gaussian-over-anchors) target.
    if nargin < 8, Xval = []; Tval = []; end
    layers = [
        imageInputLayer([nRows nFreq 1], 'Normalization', 'zscore', 'Name', 'input')
        convolution2dLayer([min(4,nRows) 20], cfg.Conv1, 'Padding', 'same', 'Name', 'conv1')
        batchNormalizationLayer('Name', 'bn1'); reluLayer('Name', 'relu1')
        convolution2dLayer([min(2,nRows) 10], cfg.Conv2, 'Padding', 'same', 'Name', 'conv2')
        batchNormalizationLayer('Name', 'bn2'); reluLayer('Name', 'relu2')
        fullyConnectedLayer(cfg.FC1, 'Name', 'fc1')
        batchNormalizationLayer('Name', 'bn3'); reluLayer('Name', 'relu3')
        dropoutLayer(cfg.Dropout, 'Name', 'dropout')
        fullyConnectedLayer(G, 'Name', 'fc_out')
        softmaxLayer('Name', 'softmax')
        regressionLayer('Name', 'output')];
    if cfg.showPlots, plt = 'training-progress'; else, plt = 'none'; end
    args = {'MaxEpochs', cfg.Epochs, 'MiniBatchSize', cfg.BatchSize, ...
        'InitialLearnRate', cfg.LR, 'LearnRateSchedule', 'piecewise', ...
        'LearnRateDropPeriod', cfg.LRDropPeriod, 'LearnRateDropFactor', cfg.LRDropFactor, ...
        'Shuffle', 'every-epoch', 'ExecutionEnvironment', execEnv, 'Verbose', false, 'Plots', plt};
    if ~isempty(Xval)
        iterPerEpoch = max(1, floor(size(XTrain, 4) / cfg.BatchSize));
        args = [args, {'ValidationData', {Xval, Tval}, 'ValidationFrequency', iterPerEpoch, ...
                       'ValidationPatience', Inf, 'OutputNetwork', 'best-validation'}];
    end
    net = trainNetwork(XTrain, Tsoft, layers, trainingOptions('adam', args{:}));
end

function [Xt, Tt, Xv, Tv] = posDisjointSplit(X, T, labels, frac)
% Split a training set so that a fraction of the POSITIONS (all their trials)
% become a validation set disjoint from training. Model selection on this set
% rewards generalization to unseen positions, not memorized ones.
    Xv = []; Tv = [];
    if frac <= 0, Xt = X; Tt = T; return; end
    u = unique(labels);
    if numel(u) < 3, Xt = X; Tt = T; return; end     % too few to spare
    nv = min(numel(u) - 1, max(1, round(frac * numel(u))));
    p = randperm(numel(u));
    valpos = u(p(1:nv));
    isval = ismember(labels, valpos);
    Xt = X(:, :, :, ~isval); Tt = T(~isval, :);
    Xv = X(:, :, :,  isval); Tv = T( isval, :);
end

function S = distStats(errs, sprs, half)
    if isempty(errs)
        S = struct('n', 0, 'medianErrIn', NaN, 'meanErrIn', NaN, ...
                   'pctWithinHalfIn', NaN, 'pctWithin1In', NaN, 'medianSpreadIn', NaN);
        return;
    end
    S.n = numel(errs);
    S.medianErrIn = median(errs); S.meanErrIn = mean(errs);
    S.pctWithinHalfIn = 100 * mean(errs <= half); S.pctWithin1In = 100 * mean(errs <= 1.0);
    S.medianSpreadIn = median(sprs);
end

function T = labelsToXY(labels, adjMap)
    T = zeros(numel(labels), 2);
    for i = 1:numel(labels), T(i, :) = labelToXY(labels{i}, adjMap); end
end

function xy = labelToXY(lbl, adjMap)
    if isKey(adjMap, lbl), xy = adjMap(lbl); return; end
    tok = regexp(lbl, 'R(\d+)C(\d+)P(\d+)', 'tokens'); t = tok{1};
    r = str2double(t{1}); c = str2double(t{2}); p = str2double(t{3});
    sp = 0.375; off = [-sp -sp; +sp -sp; +sp +sp; -sp +sp];
    xy = [(c - 0.5) + off(p, 1), (r - 0.5) + off(p, 2)];
end

function [sessions, names] = loadAllSessions(parentDir)
    d = dir(parentDir); subs = d([d.isdir] & ~ismember({d.name}, {'.', '..'}));
    filt = strtrim(getenv('CNN_LOSO_SESSIONS'));
    if ~isempty(filt)
        toks = strsplit(filt, {' ', ','}); toks = toks(~cellfun(@isempty, toks));
        keep = false(1, numel(subs));
        for ii = 1:numel(subs)
            for tt = 1:numel(toks)
                if contains(subs(ii).name, toks{tt}), keep(ii) = true; break; end
            end
        end
        subs = subs(keep);
        fprintf('[filter] CNN_LOSO_SESSIONS=%s -> %d folders\n', filt, numel(subs));
    end
    remapStr = strtrim(getenv('CNN_LOSO_PORT_REMAP')); rowperm = [];
    if ~isempty(remapStr)
        R = str2num(remapStr); rowperm = zeros(1, 32); %#ok<ST2NM>
        for a = 1:4, for b = 1:4
            nidx = (b-1)*4 + a; oidx = (R(b)-1)*4 + R(a);
            rowperm(2*nidx-1) = 2*oidx-1; rowperm(2*nidx) = 2*oidx;
        end, end
        fprintf('[remap] CNN_LOSO_PORT_REMAP=%s\n', remapStr);
    end
    sessions = {}; names = {};
    for i = 1:numel(subs)
        p = fullfile(parentDir, subs(i).name);
        if ~isempty(dir(fullfile(p, 'R*C*P*_T*.csv')))
            try
                L = loadHunterVnaFolder(p);
                if ~isempty(rowperm), L = permuteSessionRows(L, rowperm); end
                sessions{end+1} = L; names{end+1} = subs(i).name; %#ok<AGROW>
            catch ME
                fprintf('  SKIP %s (%s)\n', subs(i).name, ME.message);
            end
        end
    end
end

function L = permuteSessionRows(L, rowperm)
    for p = 1:size(L.data, 1)
        for t = 2:size(L.data, 2)
            M = L.data{p, t};
            if ~isempty(M) && size(M, 1) == numel(rowperm), L.data{p, t} = M(rowperm, :); end
        end
    end
    if isfield(L, 'baseline') && size(L.baseline, 1) == numel(rowperm)
        L.baseline = L.baseline(rowperm, :);
    end
    if isfield(L, 'baselineAll') && ~isempty(L.baselineAll) && size(L.baselineAll, 1) == numel(rowperm)
        L.baselineAll = L.baselineAll(rowperm, :, :);
    end
end

function [rows, names, pairs] = antennaRows(ports, reflOnly)
    if nargin < 2, reflOnly = false; end
    rows = []; names = {}; pairs = [];
    for i = ports, for j = ports
        if reflOnly && i ~= j, continue; end
        idx = (j-1)*4 + i;
        rows(end+1) = 2*idx-1; rows(end+1) = 2*idx; %#ok<AGROW>
        names{end+1} = sprintf('S%d%d', i, j); %#ok<AGROW>
        pairs(end+1, :) = [2*idx-1, 2*idx]; %#ok<AGROW>
    end, end
    [rows, ~] = sort(rows); names = unique(names, 'stable');
end

function S = buildSession(loaded, pairs, inputMode, nTdr, meanSub)
    data = loaded.data; baseline = loaded.baseline;
    nPos = size(data, 1); trialCount = loaded.trialCount; nFreq = loaded.numFreqPoints;
    K = size(pairs, 1);
    baseC = zeros(K, nFreq);
    for k = 1:K
        baseC(k, :) = baseline(pairs(k,1), :) .* exp(1j * deg2rad(baseline(pairs(k,2), :)));
    end
    Yall = zeros(K, nFreq, nPos * trialCount); posLabel = cell(nPos * trialCount, 1); n = 0;
    for p = 1:nPos
        lbl = data{p, 1};
        for t = 1:trialCount
            raw = data{p, t+1};
            if isempty(raw) || any(isnan(raw(:))), continue; end
            n = n + 1; Sc = zeros(K, nFreq);
            for k = 1:K
                Sc(k, :) = raw(pairs(k,1), :) .* exp(1j * deg2rad(raw(pairs(k,2), :)));
            end
            Yall(:, :, n) = Sc - baseC; posLabel{n} = lbl;
        end
    end
    Yall = Yall(:, :, 1:n); posLabel = posLabel(1:n);
    if meanSub, Yall = Yall - mean(Yall, 3); end
    switch inputMode
        case 'raw',     nRows = 2 * K; W = nFreq;
        case 'physics', nRows = 5 * K; W = nFreq;
        case 'tdr',     nRows = K;     W = nTdr;
        otherwise, error('unknown CNN_LOSO_INPUT %s', inputMode);
    end
    X = zeros(nRows, W, 1, n);
    for i = 1:n
        block = zeros(nRows, W);
        for k = 1:K
            yv = Yall(k, :, i); env = abs(ifft(yv));
            switch inputMode
                case 'raw',  block((k-1)*2 + (1:2), :) = [abs(yv); angle(yv)];
                case 'tdr',  block(k, :) = env(1:nTdr);
                case 'physics'
                    envpad = zeros(1, nFreq); envpad(1:nTdr) = env(1:nTdr);
                    block((k-1)*5 + (1:5), :) = [abs(yv); angle(yv); real(yv); imag(yv); envpad];
            end
        end
        X(:, :, 1, i) = block;
    end
    if n > 1, X = (X - mean(X, 4)) ./ (std(X, 0, 4) + 1e-8); end
    S.X = X; S.posLabel = posLabel;
end

function net = trainCNNReg(XTrain, TTrain, nRows, nFreq, cfg, execEnv, Xval, Tval)
    if nargin < 8, Xval = []; Tval = []; end
    layers = [
        imageInputLayer([nRows nFreq 1], 'Normalization', 'zscore', 'Name', 'input')
        convolution2dLayer([min(4,nRows) 20], cfg.Conv1, 'Padding', 'same', 'Name', 'conv1')
        batchNormalizationLayer('Name', 'bn1'); reluLayer('Name', 'relu1')
        convolution2dLayer([min(2,nRows) 10], cfg.Conv2, 'Padding', 'same', 'Name', 'conv2')
        batchNormalizationLayer('Name', 'bn2'); reluLayer('Name', 'relu2')
        fullyConnectedLayer(cfg.FC1, 'Name', 'fc1')
        batchNormalizationLayer('Name', 'bn3'); reluLayer('Name', 'relu3')
        dropoutLayer(cfg.Dropout, 'Name', 'dropout')
        fullyConnectedLayer(2, 'Name', 'fc_out')
        regressionLayer('Name', 'output')];
    if cfg.showPlots, plt = 'training-progress'; else, plt = 'none'; end
    args = {'MaxEpochs', cfg.Epochs, 'MiniBatchSize', cfg.BatchSize, ...
        'InitialLearnRate', cfg.LR, 'LearnRateSchedule', 'piecewise', ...
        'LearnRateDropPeriod', cfg.LRDropPeriod, 'LearnRateDropFactor', cfg.LRDropFactor, ...
        'Shuffle', 'every-epoch', 'ExecutionEnvironment', execEnv, 'Verbose', false, 'Plots', plt};
    if ~isempty(Xval)
        % position-disjoint validation: keep the best-validation network, no
        % early stop (isolate model SELECTION, not shortened training).
        iterPerEpoch = max(1, floor(size(XTrain, 4) / cfg.BatchSize));
        args = [args, {'ValidationData', {Xval, Tval}, ...
                       'ValidationFrequency', iterPerEpoch, ...
                       'ValidationPatience', Inf, ...
                       'OutputNetwork', 'best-validation'}];
    end
    opts = trainingOptions('adam', args{:});
    net = trainNetwork(XTrain, TTrain, layers, opts);
end
