% =========================================================================
% AI ACKNOWLEDGMENT: This code was generated by Claude (Anthropic) with
% inputs and direction from Peter Martin.
%
% Imager_CNN_SimReg.m  --  3D (x,y,z) tumor localization on SIMULATED data
%
% Reuses the measured-data regression CNN on the SamMakin HFSS tumor sweep.
% One simulated phantom, the tumor moved over ~738 positions at several depths;
% one deterministic S-parameter result per position (no sessions, no trials).
%
% Differences from the measured pipeline (Imager_CNN_RegLOSO/RegLOPO):
%   * Input   : 4-port Touchstone (.s4p), differential dS = S - S_empty
%               (each folder's own baseline_empty.s4p). Raw mag/phase image,
%               freq resampled to SIM_NFREQ points over 2-8 GHz.
%   * Head    : fc(3) -> regression  (predict x, y, z in mm).
%   * Protocol: 8-fold POSITION cross-validation (true 738-fold leave-one-
%               position-out is infeasible). Same "predict positions not in
%               training" interpolation question, ~90x cheaper.
%   * Metrics : LATERAL error sqrt(dx^2+dy^2) and DEPTH error |dz| reported
%               SEPARATELY (mm) -- a planar array resolves xy far better than z.
%
% Feasibility (sim_feasibility_check.py) already confirmed the signal is
% learnable: k-NN localizes xy to ~3.3 mm, z to ~1.7-3.3 mm (vs ~35 / ~6 mm
% chance). Mixup (MIXUP_ALPHA) optional; it helped interpolation on measured.
%
% ENV VARS: SIM_KFOLD (default 8), CNN_LOSO_EPOCHS (default 60),
%           SIM_NFREQ (default 256), MIXUP_ALPHA (default 0 = off).
% Output: ../results/cnn_simreg_<tag>.json (+ .mat, error-map figures).
% =========================================================================

clear; clc; close all;
fprintf('================================================================\n');
fprintf('  Imager CNN  --  3D (x,y,z) tumor localization on SIM data\n');
fprintf('================================================================\n\n');

%% CONFIG
cfg.LR = 1e-3; cfg.BatchSize = 16; cfg.Epochs = 60;
cfg.Conv1 = 32; cfg.Conv2 = 32; cfg.FC1 = 64; cfg.Dropout = 0.3;
cfg.LRDropFactor = 0.5; cfg.LRDropPeriod = 25; cfg.showPlots = false;
if ~isempty(getenv('CNN_LOSO_EPOCHS')), cfg.Epochs = str2double(getenv('CNN_LOSO_EPOCHS')); end
KFOLD = 8;  if ~isempty(getenv('SIM_KFOLD')),  KFOLD  = str2double(getenv('SIM_KFOLD'));  end
simCV = lower(strtrim(getenv('SIM_CV'))); if isempty(simCV), simCV = 'kfold'; end  % kfold | depth
NFREQ = 256; if ~isempty(getenv('SIM_NFREQ')), NFREQ = str2double(getenv('SIM_NFREQ')); end
mixAlpha = str2double(getenv('MIXUP_ALPHA')); if isnan(mixAlpha), mixAlpha = 0; end
rng(42);
if usejava('desktop'), figVis = 'on'; else, figVis = 'off'; end

thisDir = fileparts(mfilename('fullpath')); if isempty(thisDir), thisDir = pwd; end
resultsDir = fullfile(fileparts(thisDir), 'results');
if ~isfolder(resultsDir), mkdir(resultsDir); end

% Consolidated tumor sweep (all depths in one folder) with PER-BATCH empty
% baselines: each depth came from one HFSS batch, so the differential dS must
% subtract that batch's baseline. z=3 mm is off the 5 mm depth grid (a leftover
% odd depth) and is EXCLUDED by default.
SIM_DIR = getenv('SIM_DIR');
if isempty(SIM_DIR)
    SIM_DIR = ['C:\Users\peter\Desktop\EM Imaging\Simulation Data\SamMakin\' ...
               'Data Results\A3_Metal_1cm'];
end
EXCLUDE_Z = 3; if ~isempty(getenv('SIM_EXCLUDE_Z')), EXCLUDE_Z = str2double(getenv('SIM_EXCLUDE_Z')); end
grid = linspace(2e9, 8e9, NFREQ);

% depth (mm) -> batch baseline file  (z=3 would be Depth3, but it's excluded)
baseMap = { [0 5 10],           'baseline_empty_b1.s4p'; ...
            [-5 15 20 25 30],   'baseline_empty_b1_2.s4p'; ...
            [-15 -10 35 40 45], 'baseline_empty_b1_3.s4p' };

%% 1. LOAD  (differential dS -> raw mag/phase image)
% Baseline: a single baseline_empty.s4p if present (e.g., beet), otherwise the
% per-batch map above (metal, where each depth came from a different HFSS batch).
fprintf('--- Loading s4p from %s ---\n', SIM_DIR);
singlePath = fullfile(SIM_DIR, 'baseline_empty.s4p');
useSingle = isfile(singlePath);
if useSingle
    [fb, Sb] = readTouchstoneMA(singlePath);
    SbSingle = resampleC(fb, Sb, grid);
    fprintf('    baseline: single (baseline_empty.s4p);  excluding z=%g mm\n', EXCLUDE_Z);
else
    Sb_g = cell(size(baseMap, 1), 1);
    for b = 1:size(baseMap, 1)
        [fb, Sb] = readTouchstoneMA(fullfile(SIM_DIR, baseMap{b, 2}));
        Sb_g{b} = resampleC(fb, Sb, grid);
    end
    fprintf('    baseline: per-batch (%d);  excluding z=%g mm\n', size(baseMap,1), EXCLUDE_Z);
end
Xc = {}; T = []; nExcl = 0; nNoBase = 0;
files = dir(fullfile(SIM_DIR, 'P*.s4p'));
for k = 1:numel(files)
    [xyz, ok] = posFromName(files(k).name);
    if ~ok, continue; end
    z = round(xyz(3));
    if z == EXCLUDE_Z, nExcl = nExcl + 1; continue; end
    if useSingle
        SbUse = SbSingle;
    else
        bi = 0;
        for b = 1:size(baseMap, 1)
            if ismember(z, baseMap{b, 1}), bi = b; break; end
        end
        if bi == 0, nNoBase = nNoBase + 1; continue; end   % depth with no mapped baseline
        SbUse = Sb_g{bi};
    end
    [fq, S] = readTouchstoneMA(fullfile(SIM_DIR, files(k).name));
    if size(S, 2) ~= 16, continue; end
    S_r = resampleC(fq, S, grid);
    dS = S_r - SbUse;                                    % NFREQ x 16
    img = zeros(32, NFREQ);
    for c = 1:16
        img(2*c-1, :) = abs(dS(:, c)).';
        img(2*c,   :) = angle(dS(:, c)).';
    end
    Xc{end+1} = img;   %#ok<AGROW>
    T(end+1, :) = xyz; %#ok<AGROW>
end
fprintf('  excluded z=%g: %d    unmapped-depth skipped: %d\n', EXCLUDE_Z, nExcl, nNoBase);
N = size(T, 1);
if N < 20, error('Too few positions loaded (%d).', N); end
X = zeros(32, NFREQ, 1, N);
for i = 1:N, X(:, :, 1, i) = Xc{i}; end
clear Xc;
fprintf('Loaded %d positions.  x[%.0f,%.0f] y[%.0f,%.0f] z[%.0f,%.0f] mm\n', ...
    N, min(T(:,1)),max(T(:,1)), min(T(:,2)),max(T(:,2)), min(T(:,3)),max(T(:,3)));
fprintf('CNN input image: 32 x %d   folds=%d  epochs=%d  mixup=%.2f\n', NFREQ, KFOLD, cfg.Epochs, mixAlpha);

if gpuDeviceCount > 0, execEnv = 'gpu'; else, execEnv = 'cpu'; end

%% 2. CROSS-VALIDATION  (kfold random positions, OR leave-one-depth-out)
if strcmp(simCV, 'depth')
    zvals = unique(round(T(:, 3)));
    testSets = arrayfun(@(z) find(round(T(:, 3)) == z), zvals, 'uni', 0);
    foldLabel = arrayfun(@(z) sprintf('z=%+d mm', z), zvals, 'uni', 0);
    zEdge = ismember(zvals, [min(zvals), max(zvals)]);   % edge depths = extrapolation
    fprintf('\n=== LEAVE-ONE-DEPTH-OUT (%d depths; edges = extrapolation) ===\n', numel(zvals));
else
    perm = randperm(N); foldOf = zeros(1, N);
    for i = 1:N, foldOf(perm(i)) = mod(i-1, KFOLD) + 1; end
    testSets = arrayfun(@(f) find(foldOf == f), (1:KFOLD)', 'uni', 0);
    foldLabel = arrayfun(@(f) sprintf('fold %d', f), (1:KFOLD)', 'uni', 0);
    zEdge = false(numel(testSets), 1);
    fprintf('\n=== %d-fold position cross-validation ===\n', KFOLD);
end
nFold = numel(testSets);
foldRows = struct('label', {}, 'n', {}, 'xyMedMm', {}, 'zMedMm', {}, 'isEdge', {});

pred = nan(N, 3);
for f = 1:nFold
    t0 = tic;
    teIdx = testSets{f}; trIdx = setdiff((1:N)', teIdx);
    if isempty(teIdx), continue; end
    Xtr = X(:, :, :, trIdx); Ttr = T(trIdx, :);
    Xte = X(:, :, :, teIdx);
    % per-pixel z-score from TRAIN stats (applied to train + test; no leakage)
    mu = mean(Xtr, 4); sd = std(Xtr, 0, 4) + 1e-8;
    Xtr = (Xtr - mu) ./ sd; Xte = (Xte - mu) ./ sd;
    if mixAlpha > 0, [Xtr, Ttr] = mixup3(Xtr, Ttr, mixAlpha, 1.0); end
    net = trainSimCNN(Xtr, Ttr, NFREQ, cfg, execEnv);
    pred(teIdx, :) = double(predict(net, Xte));
    xy = median(hypot(pred(teIdx,1)-T(teIdx,1), pred(teIdx,2)-T(teIdx,2)));
    zz = median(abs(pred(teIdx,3)-T(teIdx,3)));
    foldRows(end+1) = struct('label', foldLabel{f}, 'n', numel(teIdx), ...
        'xyMedMm', xy, 'zMedMm', zz, 'isEdge', logical(zEdge(f))); %#ok<SAGROW>
    tagE = ''; if zEdge(f), tagE = '  [extrap]'; end
    fprintf('  %-12s: %3d test  xy med %5.1f mm  z med %5.1f mm  (%.0fs)%s\n', ...
        foldLabel{f}, numel(teIdx), xy, zz, toc(t0), tagE);
end

%% 3. METRICS  (lateral xy and depth z, separately, in mm)
xyErr = hypot(pred(:,1)-T(:,1), pred(:,2)-T(:,2));
zErr  = abs(pred(:,3)-T(:,3));
c = mean(T, 1);
xyBase = hypot(T(:,1)-c(1), T(:,2)-c(2));
zBase  = abs(T(:,3)-c(3));
S = struct();
S.method='CNN-SIM-3D'; S.task='regression_xyz_mm';
if strcmp(simCV,'depth'), S.protocol='leave_one_depth_out'; else, S.protocol=sprintf('%dfold_position_cv',KFOLD); end
S.numPositions=N; S.nfreq=NFREQ; S.epochs=cfg.Epochs; S.mixupAlpha=mixAlpha;
S.simDir=SIM_DIR; S.excludeZ=EXCLUDE_Z; S.folds=foldRows;
S.lateral_medianMm=median(xyErr); S.lateral_meanMm=mean(xyErr);
S.lateral_pctWithin5mm=100*mean(xyErr<=5); S.lateral_pctWithin10mm=100*mean(xyErr<=10);
S.depth_medianMm=median(zErr); S.depth_meanMm=mean(zErr);
S.depth_pctWithin5mm=100*mean(zErr<=5);
S.lateral_centroidMedianMm=median(xyBase); S.depth_centroidMedianMm=median(zBase);
pp = struct('x',{},'y',{},'z',{},'predX',{},'predY',{},'predZ',{},'xyErrMm',{},'zErrMm',{});
for i=1:N
    pp(end+1)=struct('x',T(i,1),'y',T(i,2),'z',T(i,3),'predX',pred(i,1),'predY',pred(i,2), ...
        'predZ',pred(i,3),'xyErrMm',xyErr(i),'zErrMm',zErr(i)); %#ok<SAGROW>
end
S.perPosition=pp;

fprintf('\n----------------------------------------------------------------\n');
fprintf('  LATERAL (xy) error : median %.2f mm  mean %.2f  (<=5mm %.0f%%, <=10mm %.0f%%)\n', ...
    S.lateral_medianMm, S.lateral_meanMm, S.lateral_pctWithin5mm, S.lateral_pctWithin10mm);
fprintf('  DEPTH   (z)  error : median %.2f mm  mean %.2f  (<=5mm %.0f%%)\n', ...
    S.depth_medianMm, S.depth_meanMm, S.depth_pctWithin5mm);
fprintf('  centroid baseline  : xy %.1f mm   z %.1f mm\n', S.lateral_centroidMedianMm, S.depth_centroidMedianMm);
fprintf('----------------------------------------------------------------\n');

xtag = ''; if EXCLUDE_Z == 3, xtag = '_5mmgrid'; elseif ~isnan(EXCLUDE_Z), xtag = sprintf('_noZ%g', EXCLUDE_Z); end
if strcmp(simCV, 'depth')
    tag = sprintf('depthCV_nf%d%s', NFREQ, xtag);
elseif mixAlpha > 0
    tag = sprintf('%dfold_nf%d_mixup%s%s', KFOLD, NFREQ, strrep(num2str(mixAlpha), '.', 'p'), xtag);
else
    tag = sprintf('%dfold_nf%d%s', KFOLD, NFREQ, xtag);
end
simLabel = strtrim(getenv('SIM_LABEL')); if ~isempty(simLabel), tag = [tag '_' simLabel]; end
S.label = simLabel;
jsonPath = fullfile(resultsDir, sprintf('cnn_simreg_%s.json', tag));
fid=fopen(jsonPath,'w'); fprintf(fid,'%s',jsonencode(S,'PrettyPrint',true)); fclose(fid);
save(fullfile(resultsDir, sprintf('cnn_simreg_%s.mat', tag)), 'S');
fprintf('Saved %s\n', jsonPath);

% xy error map (top view) + predicted-vs-actual xy
fig = figure('Visible', figVis, 'Position', [100 100 1150 520]);
subplot(1,2,1);
scatter(T(:,1), T(:,2), 40, xyErr, 'filled'); colormap(gca, flipud(jet));
caxis([0 max(10, prctile(xyErr,90))]); cb=colorbar; cb.Label.String='lateral error (mm)';
axis equal; grid on; xlabel('X (mm)'); ylabel('Y (mm)');
title(sprintf('Lateral error map  --  median %.1f mm', S.lateral_medianMm));
subplot(1,2,2);
plot(T(:,3), pred(:,3), '.', 'MarkerSize', 8); hold on;
lim=[min(T(:,3))-3, max(T(:,3))+3]; plot(lim, lim, 'k--'); xlim(lim); ylim(lim);
axis square; grid on; xlabel('true depth z (mm)'); ylabel('predicted z (mm)');
title(sprintf('Depth: predicted vs true  --  median |dz| %.1f mm', S.depth_medianMm));
saveas(fig, fullfile(resultsDir, sprintf('cnn_simreg_%s.png', tag)));
fprintf('Saved figure.\nDone.\n');


% =========================================================================
%  LOCAL FUNCTIONS
% =========================================================================
function p = findBaseline(fdir)
    d = dir(fullfile(fdir, '**', 'baseline_empty.s4p'));
    if isempty(d), p = ''; else, p = fullfile(d(1).folder, d(1).name); end
end

function files = listPosFiles(fdir)
    d = dir(fullfile(fdir, '**', 'P*.s4p'));
    files = struct('name', {}, 'name_full', {});
    for i = 1:numel(d)
        files(end+1) = struct('name', d(i).name, ...
            'name_full', fullfile(d(i).folder, d(i).name)); %#ok<AGROW>
    end
end

function [xyz, ok] = posFromName(fn)
    fn = regexprep(fn, '\.s4p$', '', 'ignorecase');   % drop ext so Z parses
    toks = strsplit(fn, '_');
    x = NaN; y = NaN; z = NaN;
    for i = 1:numel(toks)
        t = toks{i};
        if numel(t) < 2, continue; end
        % coord tokens are exactly [XYZ][mp]<digits> (e.g. Xm5p022, Zp3p000);
        % skip label tokens like 'DenseZ3' that contain other letters.
        if ~any(t(1) == 'XYZ'), continue; end
        if ~any(t(2) == 'mp'), continue; end
        v = parseSigned(t(2:end));
        switch t(1)
            case 'X', x = v;
            case 'Y', y = v;
            case 'Z', z = v;
        end
    end
    xyz = [x y z]; ok = all(isfinite(xyz));
end

function v = parseSigned(body)
    % 'm5p022' -> -5.022 ; 'p3p000' -> 3.0 ; leading m/p = sign, other p = '.'
    v = NaN; if isempty(body), return; end
    sgn = 1;
    if body(1) == 'm', sgn = -1; body = body(2:end);
    elseif body(1) == 'p', body = body(2:end); end
    body = strrep(body, 'p', '.');
    x = str2double(body);
    if ~isnan(x), v = sgn * x; end
end

function [freq, S16] = readTouchstoneMA(path)
% 4-port MA Touchstone -> freq (nf x1) Hz, S16 (nf x 16) complex (file order).
    txt = fileread(path);
    lines = regexp(txt, '\r\n|\r|\n', 'split');
    scale = 1e9; keep = false(1, numel(lines));
    for i = 1:numel(lines)
        s = strtrim(lines{i});
        if isempty(s) || s(1) == '!', continue; end
        if s(1) == '#'
            low = lower(s);
            if contains(low,' hz') && ~contains(low,' ghz') && ~contains(low,' mhz') && ~contains(low,' khz'), scale=1;
            elseif contains(low,' khz'), scale=1e3;
            elseif contains(low,' mhz'), scale=1e6;
            else, scale=1e9; end
            continue;
        end
        lines{i} = s; keep(i) = true;
    end
    vals = sscanf(strjoin(lines(keep), ' '), '%f');
    per = 1 + 2*16; nf = floor(numel(vals)/per);
    vals = reshape(vals(1:nf*per), per, nf).';
    freq = vals(:,1) * scale;
    body = vals(:, 2:end);
    mag = body(:, 1:2:end); ang = deg2rad(body(:, 2:2:end));
    S16 = mag .* exp(1j*ang);
end

function Sg = resampleC(fq, S, grid)
% interp complex S (nf x 16) onto common freq grid -> (numel(grid) x 16)
    Sg = zeros(numel(grid), size(S,2));
    for c = 1:size(S,2)
        Sg(:,c) = interp1(fq, S(:,c), grid, 'linear', 'extrap');
    end
end

function [Xo, To] = mixup3(X, T, alpha, ratio)
    if alpha <= 0, Xo=X; To=T; return; end
    n = size(X,4); nMix = max(1, round(ratio*n));
    ii = randi(n, nMix, 1); jj = randi(n, nMix, 1);
    if exist('betarnd','file'), lam = betarnd(alpha, alpha, nMix, 1); else, lam = rand(nMix,1); end
    sz = size(X); Xmix = zeros([sz(1) sz(2) 1 nMix], 'like', X); Tmix = zeros(nMix, 3);
    for k = 1:nMix
        l = lam(k);
        Xmix(:,:,1,k) = l*X(:,:,1,ii(k)) + (1-l)*X(:,:,1,jj(k));
        Tmix(k,:)     = l*T(ii(k),:)     + (1-l)*T(jj(k),:);
    end
    Xo = cat(4, X, Xmix); To = [T; Tmix];
end

function net = trainSimCNN(XTrain, TTrain, nFreq, cfg, execEnv)
    layers = [
        imageInputLayer([32 nFreq 1], 'Normalization', 'zscore', 'Name', 'input')
        convolution2dLayer([4 20], cfg.Conv1, 'Padding', 'same', 'Name', 'conv1')
        batchNormalizationLayer('Name','bn1'); reluLayer('Name','relu1')
        convolution2dLayer([2 10], cfg.Conv2, 'Padding', 'same', 'Name', 'conv2')
        batchNormalizationLayer('Name','bn2'); reluLayer('Name','relu2')
        fullyConnectedLayer(cfg.FC1, 'Name','fc1')
        batchNormalizationLayer('Name','bn3'); reluLayer('Name','relu3')
        dropoutLayer(cfg.Dropout, 'Name','dropout')
        fullyConnectedLayer(3, 'Name','fc_out')
        regressionLayer('Name','output')];
    if cfg.showPlots, plt='training-progress'; else, plt='none'; end
    opts = trainingOptions('adam', 'MaxEpochs', cfg.Epochs, 'MiniBatchSize', cfg.BatchSize, ...
        'InitialLearnRate', cfg.LR, 'LearnRateSchedule', 'piecewise', ...
        'LearnRateDropPeriod', cfg.LRDropPeriod, 'LearnRateDropFactor', cfg.LRDropFactor, ...
        'Shuffle', 'every-epoch', 'ExecutionEnvironment', execEnv, 'Verbose', false, 'Plots', plt);
    net = trainNetwork(XTrain, TTrain, layers, opts);
end
