// Regression results deck — CNN vs MLP (x,y) localization on the A3 phantom.
// Build:  node gen_regression_deck.js   ->  Regression_Results.pptx
const pptxgen = require("pptxgenjs");

// ---- palette (deep-ocean / RF) ----
const NAVY = "0E2233", BLUE = "0B5D7A", TEAL = "1C9AA8", MINT = "2CC4A3",
      CORAL = "D64545", AMBER = "E0A100", INK = "1E293B", MUTE = "5B6B7B",
      LIGHT = "FFFFFF", CARD = "F3F7FA", LINE = "D8E2EA";
const HEAD = "Cambria", BODY = "Calibri";
const shadow = () => ({ type: "outer", color: "5B6B7B", blur: 7, offset: 3, angle: 90, opacity: 0.18 });

// ---- all numbers (canonical committed results) ----
const LOSO = {  // pos median err (in), % within half-cell (CNN values = enriched re-runs)
  cats: ["Empty", "F4 insert", "F5 insert"],
  cnnRaw: [0.154, 0.164, 0.223], mlpRaw: [0.481, 0.695, 0.759],
  centroid: [1.34, 1.73, 1.30],
};
const LOPO = { cats: ["Empty", "F4 insert", "F5 insert"],
  pooled: [0.473, 0.487, 0.667], insession: [0.661, 0.609, 0.753] };
const EXP = { cats: ["baseline", "+mixup", "+posval", "+mix&pos", "+heatmap", "+heat&mix"],
  vals: [0.664, 0.572, 0.927, 0.722, 0.895, 0.865], best: 1 };
const IMG = {  // predicted-vs-actual figures (generated by make_pred_vs_actual.py)
  losoEmpty: "pred_vs_actual_loso_empty.png",
  losoF4:    "pred_vs_actual_loso_f4.png",
  losoF5:    "pred_vs_actual_loso_f5.png",
  lopoEmpty: "pred_vs_actual_lopo_empty.png",
  lopoF4:    "pred_vs_actual_lopo_f4.png",
  lopoF5:    "pred_vs_actual_lopo_f5.png",
};
// three-across predicted-vs-actual panel
function triPanel(s, items, takeaway) {
  const iw = 3.5, ih = 3.62, gap = 0.35, tot = 3 * iw + 2 * gap, sx = (W - tot) / 2, iy = 1.92;
  items.forEach((e, i) => {
    const x = sx + i * (iw + gap);
    card(s, x - 0.12, iy - 0.14, iw + 0.24, ih + 0.7);
    s.addImage({ path: IMG[e[0]], x, y: iy, w: iw, h: ih });
    s.addText([{ text: e[1] + "   ", options: { bold: true, color: INK } },
               { text: "median " + e[2], options: { color: TEAL, bold: true } }],
      { x: x - 0.12, y: iy + ih + 0.02, w: iw + 0.24, h: 0.38, align: "center",
        fontFace: BODY, fontSize: 13, margin: 0 });
  });
  s.addText(takeaway, { x: 0.6, y: 6.72, w: W - 1.2, h: 0.5, fontFace: BODY, fontSize: 13.5,
    italic: true, color: MUTE, align: "center", margin: 0 });
}

const pres = new pptxgen();
pres.defineLayout({ name: "W", width: 13.33, height: 7.5 });
pres.layout = "W"; pres.author = "Peter Martin"; pres.title = "Regression Results";
const W = 13.33, H = 7.5;

function title(s, t, sub) {
  s.addText(t, { x: 0.6, y: 0.42, w: W - 1.2, h: 0.7, fontFace: HEAD, fontSize: 30,
    bold: true, color: INK, margin: 0 });
  if (sub) s.addText(sub, { x: 0.6, y: 1.12, w: W - 1.2, h: 0.4, fontFace: BODY,
    fontSize: 14, color: TEAL, bold: true, margin: 0 });
}
function card(s, x, y, w, h, fill) {
  s.addShape(pres.shapes.ROUNDED_RECTANGLE, { x, y, w, h, rectRadius: 0.09,
    fill: { color: fill || CARD }, line: { color: LINE, width: 1 }, shadow: shadow() });
}

// ============================================================= 1. TITLE
let s = pres.addSlide(); s.background = { color: NAVY };
s.addText("CONTINUOUS  ( x , y )  LOCALIZATION", { x: 0.9, y: 2.15, w: 11.5, h: 0.5,
  fontFace: BODY, fontSize: 15, color: MINT, bold: true, charSpacing: 3, margin: 0 });
s.addText("Regression results on the A3 phantom", { x: 0.9, y: 2.7, w: 11.5, h: 1.1,
  fontFace: HEAD, fontSize: 40, bold: true, color: LIGHT, margin: 0 });
s.addText("Predicting the target's exact inch-coordinate — CNN vs MLP, under honest cross-validation",
  { x: 0.9, y: 3.9, w: 11.2, h: 0.5, fontFace: BODY, fontSize: 16, color: "AECBD6", margin: 0 });
[["0.16 in", "best cross-session error (CNN)"],
 ["3–4×", "harder to interpolate an unseen spot"],
 ["+14%", "mixup gain on the hardest case"]].forEach((c, i) => {
  const x = 0.9 + i * 3.95;
  s.addText(c[0], { x, y: 4.85, w: 3.7, h: 0.7, fontFace: HEAD, fontSize: 30, bold: true,
    color: MINT, margin: 0 });
  s.addText(c[1], { x, y: 5.55, w: 3.7, h: 0.6, fontFace: BODY, fontSize: 12.5, color: "AECBD6", margin: 0 });
});

// ============================================================= 2. TASK + METHOD
s = pres.addSlide(); s.background = { color: LIGHT };
title(s, "From “which cell” to “exact (x, y)”",
  "Same CNN & MLP, same data, same folds — the classifier's head swapped for coordinate regression");
const steps = [
  ["Targets", "RnCmPp grid label → true (x, y) in inches (±0.375 in corner offsets, plus photo-digitized positions where the insert blocked a corner)."],
  ["Models", "CNN: conv trunk → fc(2). MLP: 3-seed ensemble. Raw S-parameter input, per-session z-score, v2 preprocessing."],
  ["Metric", "Euclidean error in inches — never snapped to a grid point. Median error + % within the 0.5 in half-cell."],
  ["Protocols", "LOSO = hold out a whole session (new scan of a known grid). LOPO = hold out a position (interpolate to an unseen spot)."],
];
steps.forEach((st, i) => {
  const y = 1.75 + i * 1.28;
  card(s, 0.6, y, W - 1.2, 1.12);
  s.addShape(pres.shapes.OVAL, { x: 0.85, y: y + 0.28, w: 0.56, h: 0.56, fill: { color: BLUE } });
  s.addText(String(i + 1), { x: 0.85, y: y + 0.28, w: 0.56, h: 0.56, align: "center",
    valign: "middle", fontFace: HEAD, fontSize: 20, bold: true, color: LIGHT, margin: 0 });
  s.addText(st[0], { x: 1.65, y: y + 0.16, w: 2.4, h: 0.8, fontFace: HEAD, fontSize: 18,
    bold: true, color: BLUE, valign: "middle", margin: 0 });
  s.addText(st[1], { x: 4.1, y: y + 0.1, w: W - 4.9, h: 0.92, fontFace: BODY, fontSize: 13.5,
    color: INK, valign: "middle", margin: 0 });
});

// ============================================================= 3. LOSO RESULTS
s = pres.addSlide(); s.background = { color: LIGHT };
title(s, "New scan of a known grid (LOSO)",
  "Median localization error — the CNN nails it; the MLP lags and physics features break it");
s.addChart(pres.charts.BAR, [
  { name: "CNN (raw)", labels: LOSO.cats, values: LOSO.cnnRaw },
  { name: "MLP (raw)", labels: LOSO.cats, values: LOSO.mlpRaw },
  { name: "predict-centre (chance)", labels: LOSO.cats, values: LOSO.centroid },
], { x: 0.6, y: 1.7, w: 7.5, h: 5.1, barDir: "col", chartColors: [BLUE, AMBER, "C3CED6"],
  showValue: true, dataLabelPosition: "outEnd", dataLabelColor: INK, dataLabelFontSize: 10,
  dataLabelFormatCode: "0.00", valAxisTitle: "median error (inches)", showValAxisTitle: true,
  valAxisTitleColor: MUTE, valAxisTitleFontSize: 12, catAxisLabelColor: INK, catAxisLabelFontSize: 13,
  valAxisLabelColor: MUTE, valGridLine: { color: "EAF0F4", size: 0.5 }, catGridLine: { style: "none" },
  showLegend: true, legendPos: "t", legendColor: INK, legendFontSize: 11, valAxisMaxVal: 2, valAxisMinVal: 0 });
// right rail
card(s, 8.5, 1.7, 4.2, 5.1);
s.addText("What it says", { x: 8.75, y: 1.9, w: 3.7, h: 0.4, fontFace: HEAD, fontSize: 16,
  bold: true, color: BLUE, margin: 0 });
s.addText([
  { text: "CNN wins everywhere — ~0.16 in on empty (a sixth of a cell), under ¼ in even on F5.", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
  { text: "Raw ≈ physics for the CNN, so raw is the pick (simpler, faster).", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
  { text: "MLP is 3–4× worse on raw; with physics it collapses to the predict-centre baseline (1.1–1.3 in).", options: { bullet: true, breakLine: true, paraSpaceAfter: 8 } },
  { text: "Opposite of classification, where physics was the MLP's best input.", options: { bullet: true } },
], { x: 8.75, y: 2.4, w: 3.7, h: 4.2, fontFace: BODY, fontSize: 13, color: INK, valign: "top", margin: 0 });

// ============================================================= 4. LOSO EXAMPLES
s = pres.addSlide(); s.background = { color: LIGHT };
title(s, "Predicted vs. actual — LOSO (all phantoms)",
  "Green diamonds = CNN prediction · circles = true position · arrow = the error");
triPanel(s, [["losoEmpty", "Empty", "0.15 in"], ["losoF4", "F4 insert", "0.16 in"], ["losoF5", "F5 insert", "0.22 in"]],
  "Across empty, small (F4) and large (F5) inserts the CNN lands within a fifth of a cell — a new measurement session is not a problem.");

// ============================================================= 5. LOPO RESULTS
s = pres.addSlide(); s.background = { color: LIGHT };
title(s, "Interpolating to an unseen location (LOPO)",
  "Hold a whole grid cell out of training — the model must predict a spot it has never seen a signature for");
s.addChart(pres.charts.BAR, [
  { name: "pooled (all sessions)", labels: LOPO.cats, values: LOPO.pooled },
  { name: "in-session (drift removed)", labels: LOPO.cats, values: LOPO.insession },
], { x: 0.6, y: 1.7, w: 7.5, h: 5.1, barDir: "col", chartColors: [TEAL, "9AC7CE"],
  showValue: true, dataLabelPosition: "outEnd", dataLabelColor: INK, dataLabelFontSize: 11,
  dataLabelFormatCode: "0.00", valAxisTitle: "median error (inches)", showValAxisTitle: true,
  valAxisTitleColor: MUTE, valAxisTitleFontSize: 12, catAxisLabelColor: INK, catAxisLabelFontSize: 13,
  valAxisLabelColor: MUTE, valGridLine: { color: "EAF0F4", size: 0.5 }, catGridLine: { style: "none" },
  showLegend: true, legendPos: "t", legendColor: INK, legendFontSize: 11, valAxisMaxVal: 1, valAxisMinVal: 0 });
card(s, 8.5, 1.7, 4.2, 5.1);
s.addText("Three findings", { x: 8.75, y: 1.9, w: 3.7, h: 0.4, fontFace: HEAD, fontSize: 16,
  bold: true, color: TEAL, margin: 0 });
s.addText([
  { text: "Interpolation is 3–4× harder than session transfer (0.45–0.75 in vs 0.16–0.22 in).", options: { bullet: true, breakLine: true, paraSpaceAfter: 9 } },
  { text: "Pooled beats in-session on all three setups — for interpolation, more data > removing drift.", options: { bullet: true, breakLine: true, paraSpaceAfter: 9 } },
  { text: "The glandular barrier surfaces: near-insert cells are now WORSE than exterior (F4 pooled 0.75 vs 0.41 in) — the reverse of LOSO.", options: { bullet: true } },
], { x: 8.75, y: 2.4, w: 3.7, h: 4.2, fontFace: BODY, fontSize: 13, color: INK, valign: "top", margin: 0 });

// ============================================================= 6. LOPO EXAMPLES
s = pres.addSlide(); s.background = { color: LIGHT };
title(s, "Predicted vs. actual — LOPO (all phantoms, unseen cells)",
  "Now predicting locations never sampled — arrows grow and pull inward; red-ringed points sit over the glandular insert");
triPanel(s, [["lopoEmpty", "Empty", "0.47 in"], ["lopoF4", "F4 insert", "0.49 in"], ["lopoF5", "F5 insert", "0.67 in"]],
  "Interpolation error climbs with insert size (0.47 → 0.49 → 0.67 in) and concentrates on the near-insert cells — the CNN can't bridge the dielectric barrier it never sampled.");

// ============================================================= 7. IMPROVING INTERPOLATION
s = pres.addSlide(); s.background = { color: LIGHT };
title(s, "Can we teach it to interpolate?",
  "Three fixes tried on the hardest case (F5 pooled/cell, baseline 0.664 in) — only one helps");
s.addChart(pres.charts.BAR, [{ name: "median error", labels: EXP.cats, values: EXP.vals }],
  { x: 0.6, y: 1.75, w: 8.0, h: 5.0, barDir: "col", chartColors: [MINT, MINT, CORAL, CORAL, CORAL, CORAL],
    showValue: true, dataLabelPosition: "outEnd", dataLabelColor: INK, dataLabelFontSize: 11,
    dataLabelFormatCode: "0.00", valAxisTitle: "median error (inches)", showValAxisTitle: true,
    valAxisTitleColor: MUTE, valAxisTitleFontSize: 12, catAxisLabelColor: INK, catAxisLabelFontSize: 12,
    valAxisLabelColor: MUTE, valGridLine: { color: "EAF0F4", size: 0.5 }, catGridLine: { style: "none" },
    showLegend: false, valAxisMaxVal: 1, valAxisMinVal: 0 });
card(s, 8.85, 1.75, 3.85, 5.0);
s.addText("Verdict", { x: 9.1, y: 1.95, w: 3.4, h: 0.4, fontFace: HEAD, fontSize: 16, bold: true, color: MINT, margin: 0 });
s.addText([
  { text: "Mixup — WIN", options: { bold: true, color: MINT, breakLine: true } },
  { text: "blend sample pairs + their (x,y): 0.664 → 0.572, and it helps the barrier region most.", options: { breakLine: true, paraSpaceAfter: 10, fontSize: 12 } },
  { text: "Position-disjoint validation — no", options: { bold: true, color: CORAL, breakLine: true } },
  { text: "starves the ~30 scarce training positions.", options: { breakLine: true, paraSpaceAfter: 10, fontSize: 12 } },
  { text: "Heatmap output — no", options: { bold: true, color: CORAL, breakLine: true } },
  { text: "centroid readout biases predictions toward centre.", options: { fontSize: 12 } },
], { x: 9.1, y: 2.45, w: 3.4, h: 4.2, fontFace: BODY, fontSize: 13, color: INK, valign: "top", margin: 0 });

// ============================================================= 8. CONCLUSIONS
s = pres.addSlide(); s.background = { color: NAVY };
s.addText("Bottom line", { x: 0.9, y: 0.75, w: 11, h: 0.8, fontFace: HEAD, fontSize: 30, bold: true, color: LIGHT, margin: 0 });
const concl = [
  ["The CNN localizes to a sixth of a cell", "≈0.16 in cross-session on the empty phantom, <¼ in with a glandular insert — regression works, and the CNN owns it."],
  ["Raw beats physics for regression", "physics features are redundant for the CNN and outright break the MLP — the reverse of the classification result."],
  ["Interpolation is a different, harder problem", "predicting an unseen location is 3–4× harder than a new scan of a known grid; the data supports the latter far better."],
  ["The glandular barrier is real & measurable", "LOPO error concentrates on near-insert cells (≈1.8× exterior) — the model can't interpolate across the dielectric jump."],
  ["Mixup is the one lever that helps", "teaching a smooth signal→coordinate map cuts error 14% and helps the barrier most; validation-splitting and heatmap output hurt."],
];
concl.forEach((c, i) => {
  const y = 1.75 + i * 1.06;
  s.addShape(pres.shapes.OVAL, { x: 0.9, y: y + 0.05, w: 0.42, h: 0.42, fill: { color: MINT } });
  s.addText(String(i + 1), { x: 0.9, y: y + 0.05, w: 0.42, h: 0.42, align: "center", valign: "middle",
    fontFace: HEAD, fontSize: 15, bold: true, color: NAVY, margin: 0 });
  s.addText([{ text: c[0] + "  —  ", options: { bold: true, color: LIGHT } },
             { text: c[1], options: { color: "AECBD6" } }],
    { x: 1.5, y: y - 0.05, w: 11.2, h: 0.95, fontFace: BODY, fontSize: 14.5, valign: "middle", margin: 0 });
});
s.addText("github.com/pmart1534/microwave-phantom-localization-cnn-mlp", { x: 0.9, y: 7.0, w: 11.5, h: 0.35,
  fontFace: BODY, fontSize: 11, color: TEAL, margin: 0 });

pres.writeFile({ fileName: "Regression_Results.pptx" }).then(f => console.log("wrote " + f));
